### ISSUE TITLE
Downloader closes after Funimation download ends

### ISSUE THREAD

**Issue by yentcadan** [hama3254/Crunchyroll-Downloader-v3.0#100]
I tried to do what you had said in last issue, using the browser inside the downloader to add the queue and download from there. But when I try this, the downloader closes after reach the 100%.

**Comment by yentcadan** [comment]
OK, I tried again in this new version (v3.6.3), and downloading each episode per time it's working, the only problem is the temp files that remains.

**Comment by hama3254** [comment]
I understand the problem, the crashes are most likely caused by the temp folder removal which is in an exception catch since v3.5.6 so if it fails the worst that happens is that the temp files might remain which need to be deleted manual then.

Can you tell me what version of windows do you have (with build number if you have windows 10) ?

**Comment by yentcadan** [comment]
Yeah I can, here it is 
![image](https://user-images.githubusercontent.com/71165561/101287739-e8006f80-37d0-11eb-9499-91cd6072338c.png)

**Comment by hama3254** [comment]
i checked on a fresh Windows (Pro)10 20H2 version (since i still use 1909) if it could be a problem with Windows but no, it just works fine. 
If you don't open any file from that folder then i can not see a reason why the delete command does not work in your case.
