### ISSUE TITLE
Can't download certain episodes from Funimation

### ISSUE THREAD

**Issue by Azul772** [hama3254/Crunchyroll-Downloader-v3.0#104]
Crunchyroll Downloader 3.6.4

I tried to download Code Geass Season 1 from Funimation and could only download the first 4 episodes. From the 5th episode and foward I kept getting the below message and I couldn't download the video.
<img width="1920" alt="error 1" src="https://user-images.githubusercontent.com/75436296/101683497-606a6900-3a3b-11eb-86cb-5cd6d8e011c9.png">

**Comment by hama3254** [comment]
You need to have a paid subscription to access this episode (at least in jap. dub as the smile indicates), then you need to login at the build in web browser of the downloader to allow me to access the data with the cookies from your account. Otherwise the funimation api sends back what you can read at the pop up box.

**Comment by Azul772** [comment]
Thank you, it worked. Made a premium account and logged to funimation using the browser on the downloader and now I can download the episodes.
