### ISSUE TITLE
how do i fix this?

### ISSUE THREAD

**Issue by jayassimha** [hama3254/Crunchyroll-Downloader-v3.0#112]
![image](https://user-images.githubusercontent.com/72295210/102457778-4ba85980-4069-11eb-858a-370c4130d6c0.png)
this is what happened
how do i fix this?

**Comment by hama3254** [comment]
You need the x86 version from the visual c++ redistributable 2019
[wich you can download here:](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

![grafik](https://user-images.githubusercontent.com/52826614/93120687-03714800-f6c4-11ea-9109-2538679ad19a.png)

**Comment by jayassimha** [comment]
nah didn't work

**Comment by jayassimha** [comment]
![image](https://user-images.githubusercontent.com/72295210/102480136-deef8800-4085-11eb-9511-8c0fd55faf11.png)
now it's saying "unable to load DLL : xul "

**Comment by hama3254** [comment]
please check if you have the `xul.dll` in the Firefox folder of the downloader
it should look like this  
![grafik](https://user-images.githubusercontent.com/52826614/102482135-0d0fa080-4063-11eb-8abd-4883b5648953.png)

**Comment by jayassimha** [comment]
![image](https://user-images.githubusercontent.com/72295210/102482454-3511fa80-4089-11eb-8ece-de6210561519.png)
ya i have that

**Comment by jayassimha** [comment]
but it isn't working

**Comment by hama3254** [comment]
Usually the visual c++ redistributable 2019 [solve this problem](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/56) and i just [had it once that i did not](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/53) and for that exact case i never got any real feedback.
Since this is an issue with the [GeckoFX libary](https://www.nuget.org/packages/Geckofx60.32/) i also have no real knowledge about what's going in it or even what it is really needs as dependencies like visual c++ redistributable 2019 which are not even listed.
I can only suggest you take a look at your antivirus or into the file properties if windows blocks it
![grafik](https://user-images.githubusercontent.com/52826614/102486319-26b3e680-4069-11eb-9dbb-3f8ee1d67d24.png)

**Comment by jayassimha** [comment]
its not blocked :(

**Comment by hama3254** [comment]
unfortunately i can not help you since even [my linux test have worked](https://www.youtube.com/watch?v=GB-lL3Hn8rQ) with just the .net framework and the visual c++ redistributable 2019 
If you can tell me what windows version you use i could try to create a Virutal computer and see if it is running on it.

**Comment by jayassimha** [comment]
Windows 10 Home

**Comment by jayassimha** [comment]
Actually it worked at beginning
but recently i replaced hdd with ssd 
from then it is not working

**Comment by hama3254** [comment]
I tried a fresh Windows 10 Home 20H2 installation and it works like it should : https://www.youtube.com/watch?v=wb2mL12oi9w

**Comment by jayassimha** [comment]
hey
i downloaded latest version of crunchyroll downloader and it worked
btw thanks!!

**Comment by hama3254** [comment]
> hey
> i downloaded latest version of crunchyroll downloader and it worked
> btw thanks!!

i don't know how but nice to hear.
