### ISSUE TITLE
Freezing video produced

### ISSUE THREAD

**Issue by MTestertoday** [hama3254/Crunchyroll-Downloader-v3.0#119]
I was surprised when I saw this downloader today so I gave it a go. I downloaded a short video but it freezes at a certain point:
https://vimeo.com/494894781

I'm not sure what the cause is but this is quite the downer so I uninstalled it.

**Comment by hama3254** [comment]
That is not an freeze, there is most likely one of the fragments from the video stream just missing. 
This might happen due to any kind of network issue, the problem the default download library i use (ffmpeg) can not retry failed fragments it just skips them.
I have made two attempts to solve this issue.

1. the hybrid mode ( https://www.youtube.com/watch?v=s_SY3RM1F3Y )
the hybrid mode opens the stream file and saves all parts to an temporary directory which allows me to have more control over the download itself, the downside if anything is wrong with the settings it might crash in the build process and you need the storage space to have cached `.ts` fragments on the drive.    

2. the error handling function 
The error handling pauses the download process and give the user the information that the set amount of fragments have failed, you can then kill the download or retry from the beginning or just ignore it (it's not perfect but a 2-10 sek skip is not that bad especially at the end of the download)

**Comment by MTestertoday** [comment]
I'll give the software another go. Hopefully these 'fragments from the video stream just missing' is not a common issue
but rather, a rarity. But you could see it's frustrating if I download 20+ videos only for most of them to have this issue.

I used GetFLV for this before it stopped being compatible with Crunchyroll. Never had this issue when downloading 20+ videos so it's quite the surprise when I encountered  'fragments from the video stream just missing'.

**Comment by x3inspire** [comment]
> I'll give the software another go. Hopefully these 'fragments from the video stream just missing' is not a common issue
> but rather, a rarity. But you could see it's frustrating if I download 20+ videos only for most of them to have this issue.
> 
> I used GetFLV for this before it stopped being compatible with Crunchyroll. Never had this issue when downloading 20+ videos so it's quite the surprise when I encountered 'fragments from the video stream just missing'.

GetFLV  is really good?

**Comment by MTestertoday** [comment]
> > I'll give the software another go. Hopefully these 'fragments from the video stream just missing' is not a common issue
> > but rather, a rarity. But you could see it's frustrating if I download 20+ videos only for most of them to have this issue.
> > I used GetFLV for this before it stopped being compatible with Crunchyroll. Never had this issue when downloading 20+ videos so it's quite the surprise when I encountered 'fragments from the video stream just missing'.
> 
> GetFLV is really good?

Doesn't work for Crunchyroll now so I don't know.

**Comment by hama3254** [comment]
> Hopefully these 'fragments from the video stream just missing' is not a common issue

I don't have any statistics about that, but I don't get that much reports for that.

> But you could see it's frustrating if I download 20+ videos only for most of them to have this issue.

If it happens that much i would check your internet for package lost or high ping that might cause  unnecessary problems or reduce the amount of downloads at the same time.

> I used GetFLV for this before it stopped being compatible with Crunchyroll. Never had this issue when downloading 20+ videos so it's quite the surprise when I encountered 'fragments from the video stream just missing'.

I don't know how there flash player worked, it might just had worked different so that error just couldn't happen, downloading a single file is different than >700 small ones.

**Comment by MTestertoday** [comment]
@hama3254 Thanks for the replies by the way. I'll close the issue for now because things seem fine.

Also, just for the record, I don't download a lot of videos at once. Almost always 1 at a time. Rarely 2-3. Thought I'd clear this up since there was ambiguity previously.
