### ISSUE TITLE
Add an auto updater 

### ISSUE THREAD

**Issue by Ever4engel** [hama3254/Crunchyroll-Downloader-v3.0#125]
Would be too difficult to add an auto-updater feature ?

**Comment by hama3254** [comment]
i tried something like that a view years ago in another project so it should be possible, but i'm not a fan of pop up messages at the start for something like that. 
If i just look at the version from v3.6.5 to v3.7 there had just the minor change to Crunchyroll that resolution not found dialog would saves the selected value, you don't needed the latest version at all time so an auto updater or a simple update information at the start might just be annoying without much benefit for the user.

**Comment by Ever4engel** [comment]
yes but it will create a big fragmentation with versions of the same software. it will end up polluting your bug-tracker for things that you already fixed in futer version etc.
and one the user end, it will be not very convenient to check everyday if there is a brand new stable version for this tool.

**Comment by hama3254** [comment]
> but it will create a big fragmentation with versions of the same software.

> it will be not very convenient to check everyday if there is a brand new stable version for this tool

there is no problem with fragmentation, if the version you are using works then you don't need to update.
If something stops working then you can always check for a new version before making a new issue, so you don't have to check every day.

> it will end up polluting your bug-tracker for things that you already fixed in future version etc

there are not that many users right now so i got 4 comment on YT and 3 issues in the last week so that is not going to happen soon. 

the only thing i would consider now is adding it like this : 
![grafik](https://user-images.githubusercontent.com/52826614/103447783-f470ce80-4c8f-11eb-949d-822eb1a6d10b.png)

**Comment by Ever4engel** [comment]
yep +1 for it at least you know that you're not up to date.

**Comment by hama3254** [comment]
it has been added with v3.7.2 :
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.2

**Comment by Ever4engel** [comment]
thanks @hama3254 :) 

that be said i close this ticket
