### ISSUE TITLE
Can't get subs by default

### ISSUE THREAD

**Issue by jayassimha** [hama3254/Crunchyroll-Downloader-v3.0#130]
after downloading an episode with soft sub the subs are not coming by default
i always have to set a subtitle track
is there a way to get subs by default in soft subs?

**Comment by hama3254** [comment]
This sounds to me like your player does not display the subtitle until you enable them, which would mean the downloader works as intended and it's player setting or issue.

**Comment by jayassimha** [comment]
i'll try with another player and inform you

**Comment by hama3254** [comment]
> why don't u try downloading with softsub and tell me

well from my point of view

>the downloader works as intended

and i would not have enough information from you anyway, i can not even tell you the lazy way to just use hardsub because i would not recommend it on funimation without nvenc enabled. 

but i did one little google search with just `default subtitle mp4` [and the fist result i get is a way to set a default tag](https://video.stackexchange.com/questions/10423/force-subtitles-to-play-as-default) on the subtitle i want but VLC just seems to ignore it for me (but it works with Kodi) so without knowing your prefered player i can not even try it for myself.

**Comment by jayassimha** [comment]
i use mpc hc

**Comment by hama3254** [comment]
> i use mpc hc
> and i want soft subs because i can edit them

so you don't even use the merge subs feature ? 

that would not only make this invalid

> but i did one little google search with just `default subtitle mp4` [and the fist result i get is a way to set a default tag](https://video.stackexchange.com/questions/10423/force-subtitles-to-play-as-default) on the subtitle i want but VLC just seems to ignore it for me (but it works with Kodi) so without knowing your prefered player i can not even try it for myself.

but also your problem 

https://user-images.githubusercontent.com/52826614/104089477-b404e800-526f-11eb-8985-37e30549348b.mp4

**Comment by jayassimha** [comment]
i use merge subs feature

**Comment by jayassimha** [comment]
https://user-images.githubusercontent.com/72295210/104092235-a6b81f80-52a8-11eb-889c-03c343f67e09.mp4

**Comment by hama3254** [comment]
> i use merge subs feature

then disable it because mpc hc ignores the default flag for subtitles anyway but it uses subtitles from the folder with the same name on it's own 

![grafik](https://user-images.githubusercontent.com/52826614/104092424-28e21d00-5284-11eb-9f6d-55406cb1971c.png)

**Comment by jayassimha** [comment]
ah never mind got a solution for that
i'm using mkvtoolnix 
and thanks for your time
