### ISSUE TITLE
resume downloads after crash?

### ISSUE THREAD

**Issue by myths420** [hama3254/Crunchyroll-Downloader-v3.0#141]
hi really like this program along with addon to load full seasons but the app crashes constantly and have to go in and remove temp files made as restarting just makes new ones. is it possible to add a resume feature or at the very least when a season crashes mid way though have the app ignore already downloaded episodes? if the program sees an episode is already downloaded it wont try to download the next one currently it just stops completely until you click cancel. if i could add whole series again and have it skip files i already have that would be great too. as it is right now downloading anything is a sit and watch. forget starting a download before bed :(

**Comment by hama3254** [comment]
New features are currently not planned since I'm focused on the base functionality with the changes to Crunchyroll (new beta website) and funimation #271.
If the temp folders and crashes are both that big of a deal i would suggest you reduce the simultaneous downloads to ensure that your computer does not get overload by the amount of threads the downloader uses.
If you still need to restart the downloads then you can suppress the "already exists" by just selecting the right episodes, with the add-on you have full control over the selection and the mass download allows to select a start and stop episode so it should not be that big of a deal.
