### ISSUE TITLE
PC crash after firefox advice that said "Warning unrresponsive scrip"

### ISSUE THREAD

**Issue by Killuad** [hama3254/Crunchyroll-Downloader-v3.0#146]
Well, i was dowloading normally, went to eat and when i check my computer it wasn't sending video to my display, when It showed something my PC wasn't responding and the screen showed the message "Warning unrresponsive scrip". I wasn't able to see the full mesage, after a couple more problems my PC turned off and when i wasn't able to turn it on again, 
I was a little scared but after a few minuts I tried again and it turned on normally.

I don't know what happened, I took a few pictures but it are blurry
![1](https://user-images.githubusercontent.com/71679711/104983969-77ee2780-59d3-11eb-98a3-aa3993cc39e2.jpeg)
![2](https://user-images.githubusercontent.com/71679711/104983983-7d4b7200-59d3-11eb-93ec-46bc96814c83.jpeg)

This is the error that i got (this isn't mine, is from YouTube but is the same besides the "scrip").

<img width="493" alt="3" src="https://user-images.githubusercontent.com/71679711/104984557-8721a500-59d4-11eb-9829-dddf6675908b.png">

I have a few questions, what happeded to me could damage my PC?, It is safe to use the program again? or i should try with a older version or wait for a new one?.

For extra informtion;  I was dowloading 12 episodes at the same time, in the queque i had about 200 episodes and I wasn't using hybrid dowload.

**Comment by hama3254** [comment]
The error message should be a normal Firefox dialogue : https://support.mozilla.org/en-US/kb/warning-unresponsive-script

That your Pc freaked out by that is strange, this message is even there to prevent or stop unresponsive JavaScripts inside the browser.

 > I have a few questions, what happeded to me could damage my PC?, It is safe to use the program again?

you are the only one to report a issue like this. i use the GeckoFX library (which is based on the Firefox core called Gecko) since v2.1 which was released in june 2019 so i guess that's really rare but i can not ensure that it will work perfectly on every system and based on your images you use 800x600 or something as resolution which makes me question what hardware you have in the computer.

> or i should try with a older version or wait for a new one?.

as i said that part was added in v2.1 and older version does not work due to changes from Crunchyroll. 
i'm also not sure what i can do about in the next version since this message is made to stop the computer/browser from freezing, i can remove it via the preferences of the gecko engine (the same way like in the Firefox page at the top) but i'm not sure if that makes it better or worse. 

>  I was dowloading 12 episodes at the same time, in the queque i had about 200 episodes

i also would not recommend that at all and especially not with low end hardware.

and i assume the other two issues are solved because you did not reply to them.

**Comment by Killuad** [comment]
I know it is very strange, I was using an ultrawide display, but my Isn't loe end hardward it isn't the most poewrfull fut it isn't low end, i would say is middle end.

But thanks for asnwerd, do you have any recomendation to prevent this?, i was thinking to put al the videos in the queque using the add on and then uninstall firefox or only desactivate the add-on.

An yes it are solved, sorry i forgot to reply and close the issues, thank you

**Comment by hama3254** [comment]
>  i was thinking to put all the videos in the queque using the add on and then uninstall firefox or only desactivate the add-on.

this has nothing to do with the normal firefox or the add-on, there is a Webbrowser build in at the downloader based on Gecko/Firefox which loads the website and extracts the required urls without getting blocked by cloudflare. 

I would say you reduce the downloads to 3 to 6 at the same time and try the v3.7.3.1 just get the `Crunchyroll.Downloader.v3.7.3.1.exe` and copy it into the existing folder of the downloader you get it from here
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.3

**Comment by Killuad** [comment]
Ok, thank you Hama

**Comment by Killuad** [comment]
Sorry, i reopened this because i think that i probably found what really happend. After some test i found that if you choose in funimation settings the option "hard subtitle (post-proccessed)" it uses a lot of resourses.

**Comment by hama3254** [comment]
That kind of CPU usage is normal since funimation has no finished hardsubs like crunchyroll does so the downloader needs to add it afterwards and post process the downloaded video stream which takes a lot of CPU power.
even my i9 9900k @4.5GHz does not like it.
![grafik](https://user-images.githubusercontent.com/52826614/105470931-77d37d80-5c9a-11eb-9db6-54c7b7baec33.png)


if you have an nvidia graphic card that [supports nvenc](https://en.wikipedia.org/wiki/Nvidia_NVENC) (mostly everting above GTX 7xx) then you also can use it for that (but is limited to two streams at the same time due to driver side limitations)

![grafik](https://user-images.githubusercontent.com/52826614/105472525-57a4be00-5c9c-11eb-8488-6228f9c3ba3f.png)


but my recommendation for that is to use merged softsubs

![grafik](https://user-images.githubusercontent.com/52826614/105471244-d26cd980-5c9a-11eb-9b13-8ae684ab0bec.png)

This will add the subtitles as text stream to the video which needs to be read by the playback device or software.

![grafik](https://user-images.githubusercontent.com/52826614/105472030-b87fc680-5c9b-11eb-83b2-9996a36ef0c6.png)

**Comment by Killuad** [comment]
Damn you have a rocket as PC, and yeah, i'll use soft subs i was using hard subs because sometimes i can't edit the subtitles with VLC and i like the default ones from funimation and crunchyroll (at least .ass subtitles and with .srt i only can modify the size). 

I only want to let you know why I think my pc crashed and idk maybe this could happen to someone else.
