### ISSUE TITLE
Funimation videos can't be downloaded

### ISSUE THREAD

**Issue by Adhit001** [hama3254/Crunchyroll-Downloader-v3.0#179]
No certificate error. Fails with addon and entering funimation links.

**Comment by hama3254** [comment]
Can you please write full sentences, otherwise I have trouble finding your issue.
I'm currently not sure if you get the certificate error from #162, #163, #165 or #169.

**Comment by Adhit001** [comment]
I didn't get any certificate errors when trying to download a video from funimation. It fails when i copy and pasted links from the chrome browser. It also fails when i use the addon. No specific errors appeared.

**Comment by hama3254** [comment]
I can just guess right now since I'm at work and don't have the option to check for myself (for the next 10 hours).
Based on the time you made the issue and that you answer could mean you are neither from the US or Latin America which makes me to think you might use a browser only VPN in chrome which does not affect the downloader so it does not has access to funimation.
The only other possibilitie is that the downloader does not work anymore which I can check after 6pm (CET)

**Comment by hama3254** [comment]
It seems that there are some issues with the merge soft subs on funimation.
i will fix that soon, in the mean time try an older version.

**Comment by hama3254** [comment]
> It seems that there are some issues with the merge soft subs on funimation.
> i will fix that soon, in the mean time try an older version.

v3.7.5.1 has been released which fixes issues with the funimation merged softsubs

**Comment by Adhit001** [comment]
Funimation videos still couldn't be downloaded.

**Comment by hama3254** [comment]
> Funimation videos still couldn't be downloaded.

Unfortunately I can not work with that kind of error description. 
It can fail at any point from invalid data to begin with (non US or LA user) to missing urls inside the API to just errors inside the processing or even just a download issue due to again a lot of possible reasons like invalid settings.

**Comment by Adhit001** [comment]
It probably fails due to my country not being able to access Funimation normally. I have to use a VPN to use the addon, and even then it doesn't work. Even copying the url and pasting it to the downloader didn't work.

**Comment by hama3254** [comment]
You need a system wide VPN to use the downloader.
The add-on just sends the urls to the downloader not any Website data.
