### ISSUE TITLE
Cloudflare - browser not work

### ISSUE THREAD

**Issue by firecrauter** [hama3254/Crunchyroll-Downloader-v3.0#19]
Hello, I am using an RDP.
And I can't enter crunchyroll by ip ban.
![image](https://user-images.githubusercontent.com/7044466/80330711-436e8600-881c-11ea-8387-bc4da06b23fa.png)

In Chrome, there is a way to bypass ip blocking, using the TouchVPN extension.
Is there a way to use chrome in CrunchyrollDownloader, while vpn is activated?

**Comment by hama3254** [comment]
I have tried to use the chromium engine inside the downloader but that did not work at all.
I don't get access to the page content and add-ons did not work anyway so I switched to the Firefox engine called "Gecko FX".
But there is the same limitation with add-ons that's why I rebuild the US unlock for example.
One idea to go around this would be to save the website in the normal browser as HTML into an 'crunchyroll.com' folder and add the local html as URL.

**Comment by hama3254** [comment]
What OS is running on the remote machine?

**Comment by firecrauter** [comment]
> What OS is running on the remote machine?

windows server 2016 standard

**Comment by hama3254** [comment]
> > What OS is running on the remote machine?
> 
> windows server 2016 standard

well then i need to inform you that in the next versions i will change a view things.
One of it is the support of Windows Server versions, they will not work anymore with v3.3 and later.
