### ISSUE TITLE
will not pull english dubs for new shows

### ISSUE THREAD

**Issue by cimmy01** [hama3254/Crunchyroll-Downloader-v3.0#190]
I have been having trouble getting the shows that have premiered in the last couple weeks to download the english dub. it is giving the warning that the selected language is unavailable and I have to select from the pull down and the only selection is null.

**Comment by hama3254** [comment]
This error message is for the sub title language set in the settings, since you can't select the Dub language at crunchyroll anyway there is no setting or check in the downloader (except for the metadata of the video file).
Just select [null](https://en.wikipedia.org/wiki/Null_pointer) because there are most likely no subtitles for a eng dub.

**Comment by hama3254** [comment]
i think this should make the error message more clear in the future 
![grafik](https://user-images.githubusercontent.com/52826614/109296188-35b8d100-7830-11eb-9663-fee4047a59e5.png)
