### ISSUE TITLE
Invalid security certificate even when using the browser add-on (I AM NOT JUST REPEATING PREVIOUS ISSUES)

### ISSUE THREAD

**Issue by PinkRei** [hama3254/Crunchyroll-Downloader-v3.0#191]
I know that you have received many issues about this, but there really doesn't seem to be any explanation for this other than it being a problem with whatever version of firefox the downloader uses.

I can access funimation completely normally using my regular firefox browser. However when I try to navigate to funimation in the downloader's browser, I get the invalid security certificate error that I'm sure you're sick of hearing about.

I then installed the browser add-on to my regular firefox, and it does work when it comes to selecting episodes on funimation and adding them to the queue in the downloader. However, when I tried to start the downloads, I get the exact same error popping up.

I know you're tired of hearing about this, but I can access funimation perfectly normally on my normal firefox browser. The only possible source for this problem IS the browser in the downloader. The specific error I received was "SEC_ERROR_UNKNOWN_ISSUER". I have looked into this error, as detailed in the next paragraph, but only you know how you have set up the browser in the downloader, so you would need to do your own research into this.

Searching for this error, I found a few different solutions. One was to click on "advanced" on the error page, and click "I accept the risk", and continue to the site. This is impossible in your browser because it does not display the same page that firefox does, only a popup window with the name of the error. I found another solution which was to go to about:config and set "security.enterprise_roots.enabled" to true, and then restart the browser. I did this, and closed and reopened the downloader, but when I reopened it, that boolean had been set back to false. I assumed you have all these settings set to be a certain way when the browser is launched? if you tell me how to edit the dll files in the firefox folder, or whatever it is that sets up these defaults, I would be happy to do that and see if changing this boolean that way fixes the problem.

I can do as much research as I can, but ultimately you are the one who put together this custom version of firefox for this downloader, so it really does need to be you who addresses this problem. I can't do anything if all the solutions I find are incompatible with the way your custom browser works.

**Comment by hama3254** [comment]
This issue in more complicated as it seems on the first look.
This is for some people only in the downloader and not in Firefox, others report that it accrues in both.
It gets even more strange because it dissipaters for some randomly (like at the end of #162).

I also tested the `security.enterprise_roots.enabled` in [v3.7.3.3](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.3.2) with no positive feedback. 

The main problem is that i never had this issue in the first place so fixing it is quite difficult.
It does not getting better because `"your browser"` is not the right term since it is just a [library ](https://www.nuget.org/packages/Geckofx60.32/) i use without knowing how it works. 
There is a reason why just three Browsers are left.
Chrome, Firefox and Safari everyone else is just a new Interface.

The only solution i can do right now is removing the Browser from the requirement for downloading.
Right now every funimation URL is opend by the GeckoFX browser and the data is used to get the direct video url it does not matter if you add it via the Downloader or the add-on.
I already tested it with the singe add mode of the add-on and it seems to work :

https://user-images.githubusercontent.com/52826614/109386194-6284eb00-78f9-11eb-8257-376956a8e5cb.mp4

**Comment by hama3254** [comment]
i upload a test version here https://github.com/hama3254/experimental-Crunchyroll-Downloader-v3.x/releases/tag/v3.7.5.x
deactivate the store version from the add-on and use the version attached in the release since it will not work otherwise.

**Comment by PinkRei** [comment]
I'm really sorry, I downloaded the crd-addon and the debug folders, but I'm not sure what to do with them. I tried to add the CRD-addon.zip to firefox as an extension but it said it was corrupt.

**Comment by PinkRei** [comment]
oh my goodness it works. Thank you so much.

**Comment by hama3254** [comment]
your personal issue is solved so i close this.
