### ISSUE TITLE
Batch/season Download

### ISSUE THREAD

**Issue by inter5tella** [hama3254/Crunchyroll-Downloader-v3.0#200]
**Is your feature request related to a problem? Please describe.**
I want to request to download the whole season by providing the link given by the provider.

**Describe the solution you'd like**
I'd copy-pasted the link of a whole season instead of a single episode, i.e. 
https://www.crunchyroll.com/de/the-quintessential-quintuplets 
instead of 
https://www.crunchyroll.com/de/the-quintessential-quintuplets/episode-9-welcome-to-class-3-1-801861

**Describe alternatives you've considered**
Alternatively, the link to the season that is given to the 'Add Video' functionality adds a 'Work Order' for each file (or adds it to the queue). That requires that its possible to add an unlimited amount of entries per season.

**Comment by hama3254** [comment]
That already has been added in v1.2 (December 2018) and has been improved ever since then.
It can also be seen in the [Video for v3.0](https://youtu.be/1g2-QQajZ5Y)
I also made an add-on more recently which allows to even select individual episodes on the crunchyroll website.
[How it is used can be seen here](https://youtu.be/ZHCH3rNWYS8) the only thing missing is that the downloader has an setting to enable the add-on (it is off by default)

**Comment by inter5tella** [comment]
Hi Hama,

I'm very sorry that I didn't recognize there's a browser add-on. All the time I just added episodes manually into the desktop application. *feels dumb*
Many thanks for making this point and this awesome feature!
