### ISSUE TITLE
Funimation download speed

### ISSUE THREAD

**Issue by Azul772** [hama3254/Crunchyroll-Downloader-v3.0#211]
Whenever I download from funimation I get these network spikes below, how do I solve this?

<img width="193" alt="error" src="https://user-images.githubusercontent.com/75436296/111378081-c6d4d800-8677-11eb-9368-50f89f3ede62.png">

I know that I can download faster because when I was downloading Please Twins and Teacher from funimation it was a constant 50 mbps. I just don't know what I need to change in order for this to happen on all funimation downloads. The same for crunchyroll downloads.

**Comment by Azul772** [comment]
I have version 3.7.2.1

**Comment by hama3254** [comment]
The download speed is determined by many factors.
The only one you can change easily is to switch on Hybrid mode.
The hybrid mode caches the stream before the multi media library converts all small fragments to a single file.
Something else that might has an impact on your site is the connection to the router.
I would always prefer a wired ethernet connection.
Otherwise it just gets down to the video itself.
How many fragments it has, the server it is stored on and your internet connection.

**Comment by Azul772** [comment]
Thanks
