### ISSUE TITLE
download stops at around 15 mins in

### ISSUE THREAD

**Issue by kingbroseph2594** [hama3254/Crunchyroll-Downloader-v3.0#23]
i havent gotten a single download finished, don't get me wrong I'm very impressed that you guys can do what you do but due to my slow network it takes quite a while to get things done quickly and around 15 minutes into the download everything just stops and I don't know what the problem is

**Comment by hama3254** [comment]
That's an unusual error, with a slow internet speed is may take a while but even if one of the over 100 small parts of the video gets a timeout due to slow internet it just should finish and have a view seconds corrupted.
Since the download itself gets done by the ffmpeg.exe I have no much information what is going wrong at your side.
I can give you some tips like try a lower resolution and do just one download at the time.

**Comment by kingbroseph2594** [comment]
ye im doing 360 p and its better but I cant do over 2 downloads at a time
just have to deal with it I guess :P

**Comment by hama3254** [comment]
>ok thanks but im pretty sure ive figured out the problem, basically I'm downloading to an external drive and I'm pretty sure the >contact points are kinda crappy so as soon as it "disconnects" for like a little while it stops and doesn't continue but now i just >download straight to my computer then copy it onto my microSD :):)

_Originally posted by @kingbroseph2594 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/26#issuecomment-642505700_
