### ISSUE TITLE
Error download for some Anime on Crunchyroll

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#234]
Hi, tried to download this Aniem but getting error as attached.

https://www.crunchyroll.com/marudase-kintaro

![Capture](https://user-images.githubusercontent.com/4635825/112740988-1ee2d700-8fb4-11eb-8616-4c183618f5ee.JPG)

**Comment by hama3254** [comment]
I can not test Premium episodes currently because i'm opt in at the new beta website and it redirects me.
It looks to that there is missing a bunch of data for that episode, you can try to give it a name for yourself in the add video window-
![grafik](https://user-images.githubusercontent.com/52826614/112748035-7f284780-8fb9-11eb-9579-cdb2ce0da612.png)

**Comment by unbekannt1753** [comment]
I have the same issue with Naruto shippuden season Naruto Shippuden: The Master's Prophecy and Vengeance (6) episodes 115 to 118

https://www.crunchyroll.com/naruto-shippuden/episode-118-formation-530550

**Comment by hama3254** [comment]
This should be fixed in the latest beta version
