### ISSUE TITLE
Problems with a series with a tittle like as "SHORTNAME -name..."

### ISSUE THREAD

**Issue by PanchoArancibia** [hama3254/Crunchyroll-Downloader-v3.0#243]
I found a problem for titles that have the '**-**' symbol followed by the name of the series, when trying to download, it considers that it is an option in the execution (I attach an image of the log).
Specifically, it happened to me with KONOSUBA (all its versions start with "_KONOSUBA -God's..._") and then I replicated that with series that had that combination in their title. 

![problema](https://user-images.githubusercontent.com/7606390/113923441-88ce5e00-97b6-11eb-825f-675a20f6d5ea.png)

Thank you very much for all the time you have dedicated to the project. We really appreciate it!

**Comment by hama3254** [comment]
Since you did not add the version you are using I can only assume that it's the v3.8-beta.
You also did not mention if it is a crunchyroll, crunchyroll beta or funimation download so I go with the regular crunchyroll because there is definitely a issue in the code for the normal crunchyroll which breaks the file path creation resulting in a path without quotation marks and filename.
That with subfolders could lead to the issue you see.
You can only go back and use the last release version for now.

**Comment by PanchoArancibia** [comment]
> Since you did not add the version you are using I can only assume that it's the v3.8-beta.
> You also did not mention if it is a crunchyroll, crunchyroll beta or funimation download so I go with the regular crunchyroll because there is definitely a issue in the code for the normal crunchyroll which breaks the file path creation resulting in a path without quotation marks and filename.
> That with subfolders could lead to the issue you see.
> You can only go back and use the last release version for now.

I apologize for not having indicated that (v3.8-beta and from Crunchyroll). 
I'll go back to the stable version for now and thank you very much for responding.
Best regards!

**Comment by hama3254** [comment]
fixed in new beta release
