### ISSUE TITLE
Funimation Hybrid Mode

### ISSUE THREAD

**Issue by hama3254** [hama3254/Crunchyroll-Downloader-v3.0#256]
Due to changes from Funimation that can be seen in #249 the Hybrid mode does not work for mostly newer Episodes on Funimation.

The current Issue with the hybrid mode is that the audio does not get processed by the multi media library. 

>Don't be surprised if you find that FFMPEG thinks there's invalid data in
the audio stream.  I don't know what Funimation has done to those, but with
the two I've played around with so far, both had what FFMPEG thought was a
corrupted audio frame about five minutes in, so the audio cuts out after
that, even in "stream copy" mode, which is just *fantastic.*

_Originally posted by @lemming104 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/249#issuecomment-820710034_

I don't know where the error is to be found since the direct download with ffmpeg works fine it's just ridiculous slow.
If i try to cache it like with the hybrid mode i get the same issue as described by @lemming104 

>No, I just let it auto-detect.  However, even if I _do_ specify the bitstream filter, it still fails after ~5 minutes of audio.  For example, here's what I get if I run FFMPEG on the audio from "Super Cub" episode 2 (which I've already decrypted, and it plays correctly in VLCPlayer and various other applications):

```
.\ffmpeg.exe -i 'D:\Media\Super Cub Episode 2\audio_decrypted.aac' -bsf:a aac_adtstoasc -c copy 'D:\media\Super Cub Episode 2\audio_decap.aac'
ffmpeg version N-100635-gbf1cc9a43b Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration:
  libavutil      56. 63.101 / 56. 63.101
  libavcodec     58.117.101 / 58.117.101
  libavformat    58. 65.101 / 58. 65.101
  libavdevice    58. 11.103 / 58. 11.103
  libavfilter     7. 95.100 /  7. 95.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
[aac @ 00000267b2487d80] Format aac detected only with low score of 1, misdetection possible!
[aac @ 00000267b2487d80] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from 'D:\Media\Super Cub Episode 2\audio_decrypted.aac':
  Duration: 00:23:51.56, bitrate: 134 kb/s
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 134 kb/s
File 'D:\media\Super Cub Episode 2\audio_decap.aac' already exists. Overwrite? [y/N] Y
Output #0, adts, to 'D:\media\Super Cub Episode 2\audio_decap.aac':
  Metadata:
    encoder         : Lavf58.65.101
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 134 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
D:\Media\Super Cub Episode 2\audio_decrypted.aac: Invalid data found when processing input
size=    4880kB time=00:05:05.98 bitrate= 130.6kbits/s speed=1.16e+04x
video:0kB audio:4782kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.050685%
```
>The resulting audio file is ~5 minutes long, so FFMPEG clearly just bails out rather than continuing after the malformed data.

>If I get some time to do so, I may write some code to walk through the ADTS stream and copy only "well formed" frames.

_Originally posted by @lemming104 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/249#issuecomment-821233595_

**Comment by lemming104** [comment]
For the record, I've yet to find a GOOD way to recover from this; most of the free-and-open-source tools I've tried for extracting the data from the ADTS will either fail to process these streams, or will do something weird that results in audio desyncing when it's muxed back in via FFMPEG.  FFMPEG also doesn't seem to obey `-err_detect ignore_err` in this context, so I can't just brute force it.

I've also found that, if you download the .aac file EXACTLY the way specified in the .m3u8 (that is, using the HTTP RANGE header to get individual byte ranges from the file, rather than trying to download the whole file in one shot), you still end up with this problem.  So, it doesn't seem like Funimation is using discontinuities in the byte stream to "jump" over malformed or corrupted data.

The best option I've found so far, in my own project, is to decrypt and concatenate the stream files while downloading, leaving a single .ts file, zero or one .aac files (Crunchyroll still keeps audio and video together in the .ts, Funimation has just now started doing independent streams), and some subtitle files, all of which can be processed by tools that do not necessarily understand the .m3u8 playlist format or know how to decrypt AES.  Then, I use FFMPEG to convert the .ts file to .mp4, and MKVMerge to splice it all together into an .mkv.  MKVMerge apparently either doesn't notice the ADTS stream corruption, or doesn't _care_.

Funimation's change to independent streams is actually a _nice_ thing, in the sense that you can theoretically have the same video file with different audio tracks.  If they're doing it right, they probably no longer have to store the video twice for "Japanese" versus "dubbed" audio; probably saves them a lot of space on their servers.

**Comment by hama3254** [comment]
i found a way but that would double cache the file (which is not as bad for just the ~20MB audio file).
i split the file into the byte segments listed in the m3u8 file and get a new m3u8 from it. 


<details>
 <summary>VB.net Code</summary>
  

  ```
 ServicePointManager.Expect100Continue = True
        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

        Dim AudioKeyFilePath As String = "E:\Test\fun\audio.key" 'needs to be in the ffmpeg/downloader directory
        Dim AudioFilePath As String = "E:\Test\fun\audio.aac"

        Dim Client As New WebClient
        Client.Encoding = Encoding.UTF8
        Client.Headers.Add("User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0") 'they refuse the connection with some kind of user agent 

        Dim m3u8Text As String = Client.DownloadString("[some new audio m3u8 url]")

        Dim m3u8Key() As String = m3u8Text.Split(New String() {"URI=" + Chr(34)}, System.StringSplitOptions.RemoveEmptyEntries)
        Dim m3u8Key2() As String = m3u8Key(1).Split(New String() {Chr(34)}, System.StringSplitOptions.RemoveEmptyEntries)
        Client.DownloadFile(m3u8Key2(0), AudioKeyFilePath)

        Dim AudioFile() As String = m3u8Text.Split(New String() {"https://"}, System.StringSplitOptions.RemoveEmptyEntries)
        Dim AudioFile2() As String = AudioFile(2).Split(New String() {vbLf}, System.StringSplitOptions.RemoveEmptyEntries)
        Client.DownloadFile(New Uri("https:\\" + AudioFile2(0)), AudioFilePath)

        Dim text() As String = m3u8Text.Split(New String() {vbLf}, System.StringSplitOptions.RemoveEmptyEntries)
        Dim zeile As String
        Dim Count As Integer = 0

        Dim Bytes() As Byte = File.ReadAllBytes(AudioFilePath)

        For i As Integer = 0 To text.Count - 1
            zeile = text(i)
            If zeile.Contains("#EXT-X-BYTERANGE:") Then
                Dim Zeile2 As String = zeile.Replace("#EXT-X-BYTERANGE:", "")
                Dim Zeile3() As String = Zeile2.Split(New String() {"@"}, System.StringSplitOptions.RemoveEmptyEntries)

                Dim CurrentSize As Integer = Integer.Parse(Zeile3(1))
                Dim NewBytes As Integer = Integer.Parse(Zeile3(0))

                Dim bytearray(NewBytes) As Byte
                Array.Copy(Bytes, CurrentSize, bytearray, 0, NewBytes)

                File.WriteAllBytes("E:\Test\fun\Out\" + String.Format("{0:0000}", Count) + ".aac", bytearray)
                RichTextBox1.AppendText("E:\Test\fun\Out\" + String.Format("{0:0000}", Count) + ".aac")
                RichTextBox1.AppendText(vbNewLine)
                Count = Count + 1
            ElseIf zeile.Contains("URI=" + Chr(34)) Then
                Dim Zeile2() As String = zeile.Split(New String() {"URI=" + Chr(34)}, System.StringSplitOptions.RemoveEmptyEntries)
                RichTextBox1.AppendText(Zeile2(0) + "URI=" + Chr(34) + "audio.key" + Chr(34)) ' a full path does not work here
                RichTextBox1.AppendText(vbNewLine)
            ElseIf zeile.Contains("https://") Then

            Else
                RichTextBox1.AppendText(zeile)
                RichTextBox1.AppendText(vbNewLine)
            End If
        Next
  ```
</details>

**Comment by lemming104** [comment]
I've tried something like that, too, but found that FFMPEG was _still_ not happy with those audio files for some reason, which is why I gave up on letting it touch those files at all and just elected to mash everything together using mkvmerge instead.

At least with the files I've looked at so far, there are no discontinuities in the byte ranges, so you should _theoretically_ get the same result regardless of whether you download the whole thing without using ranges, download using the specified ranges and concat the files together yourself*, or download individual files using ranges and run a modified .m3u8 into FFMPEG.

Either I've missed something obvious, or FFMPEG simply does its error handling/recovery differently when downloading from a web service versus operating on local files, at least as far as ADTS-encapsulated audio goes.

*or even create your own non-overlapping ranges, so long as they're all valid offsets in the remote file.

**Comment by NatsuFT36** [comment]
It would be good to add audio conversion from 128 to 256kbps as is customary in the Funimation format.

**Comment by hama3254** [comment]
> It would be good to add audio conversion from 128 to 256kbps as is customary in the Funimation format.

I can not increase the quality, why should I bloat the file unnecessary ?

**Comment by NatsuFT36** [comment]
Well, in the torrents I saw that the audio was changed to the quality it had, although from Funimation it used to be 253-256kbps and now it went to 128-134kbps. And the torrents did it at 256kbps along with the English dub.

**Comment by lemming104** [comment]
There is no point in doing a conversion if it's not going to increase quality, and the stuff Funi has posted with independent segments so far only includes a 128kpbs AAC stream:

![image](https://user-images.githubusercontent.com/50272946/115648409-3d4da100-a2da-11eb-8870-cd5ab7b543a5.png)

Note that they _do_ have two different bandwidth levels for each video resolution; for example, they have 3.5mpbs and 2.2mbps streams for 720p.  But that's just the video.

**Comment by NatsuFT36** [comment]
Although in Funimation downloads you can make another option for hybrid downloads for the new version, you can still use 256kbps of audio with the option of "ffmpeg command".

**Comment by hama3254** [comment]
> Although in Funimation downloads you can make another option for hybrid downloads for the new version, you can still use 256kbps of audio with the option of "ffmpeg command".

There is not not 256kbps audio...
and the hybrid mode does not change anything on the output file, it is just the internal download routine.

**Comment by hama3254** [comment]
the processing of the new `#EXT-X-VERSION:4` seems to work.
now i just need to redo the old version ...
https://user-images.githubusercontent.com/52826614/115969687-77b77800-a53e-11eb-9bb8-a552b216638d.mp4

**Comment by Dantrech** [comment]
> the processing of the new `#EXT-X-VERSION:4` seems to work.
> now i just need to redo the old version ...

Excelent!

**Comment by hama3254** [comment]
everything should work again with the v3.8-Beta
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta

**Comment by NatsuFT36** [comment]
As you know, the selection of the subs formats in Funimation no longer works since the only thing that downloads is the "srt" format and not the others due to the improvement that the platform's server had.

**Comment by NatsuFT36** [comment]
But it is the most common that is used to use conversions or together with the MKV format to watch on Smart TVs.

**Comment by Gotischer** [comment]
Today when tried to download from Funimation on add video que fail? message.

**Comment by 619beave** [comment]
I'll second Gotischer's message above. I've looked inside of the PRogram folder and cannot find a log of the error.

**Comment by lemming104** [comment]
It looks like, for some reason, they changed the iframe that contains the "experience ID" used to initialize their web player.

It previously used a relative URL, e.g. ` src="/player/<experienceID>/?bdub=0" `, and now it uses an absolute URL like ` src="https://www.funimation.com/player/<experienceID>/?bdub=0" `

**Comment by hama3254** [comment]
> It looks like, for some reason, they changed the iframe that contains the "experience ID" used to initialize their web player.
> 
> It previously used a relative URL, e.g. `src="/player/<experienceID>/?bdub=0"`, and now it uses an absolute URL like `src="https://www.funimation.com/player/<experienceID>/?bdub=0"`

I use the relative one to get the `experienceID` so it does not find the video any more.
I fix that soon.

**Comment by hama3254** [comment]
> It looks like, for some reason, they changed the iframe that contains the "experience ID" used to initialize their web player.

The reason might be that as far i can see everything is now loaded via JavaScript, they might need that absolute url for that.
This is a issue on it's own so #271 is for that.
