### ISSUE TITLE
Changing temp file folder option and support mewatch.sg

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#273]
Hi, i have 2 request here. Since i'm using VPN to download from CR so i sync the folder using google drive/one drive.

1) Possible to make option to change the temp folder instead of same folder for .mp4 file? So i can exclude temp file from syned.
2) Can support mewatch.sg ? I can download the mp4 file using IDM without any problem, so i think your program also can support it.

Thanks.

**Comment by hama3254** [comment]
The fist thing is just a personal issue, the worst thing you have to do which would fix it is just use another folder for the download and manuely copy the finished files to your synced one.
Depending on the software you also might have the option to blacklist files\folders with a name pattern.

For the site request i don't add any new sites since I have enough to do with the existing ones.

**Comment by MSI-Toby** [comment]
YouTube-LD supports meWatch (https://github.com/ytdl-org/youtube-dl)
