### ISSUE TITLE
Has no items in cache but every download is stopped by a items in cache warning

### ISSUE THREAD

**Issue by cimmy01** [hama3254/Crunchyroll-Downloader-v3.0#28]
Not sure how to clear the download cache. Im running the newest version as of 6/15 but the downloader is claiming that there are items in the cache.

**Comment by hama3254** [comment]
> Not sure how to clear the download cache. Im running the newest version as of 6/15 but the downloader is claiming that there are items in the cache.

I'm not really sure to what you are referring with "cache".
I can just imagine you mean the queue ?
Then the status would display: "Status: items in queue, click to work off." .
This happens if you add more episodes then you have set to be downloaded at the same time, you can switch to the list with a click on the message itself and remove entries with a double click on the url.
Keep in mind it does start to download the items on the list from moment it is displayed, so you should have enough downloads running to be at your set limit.

**Comment by cimmy01** [comment]
sorry I work 3rd shift and ment Queue. I dont have anything in the queue and it still is claiming I do That is what Im trying to reset

**Comment by hama3254** [comment]
> sorry I work 3rd shift and ment Queue. I dont have anything in the queue and it still is claiming I do That is what Im trying to reset

That weird, it should not display the message if it is empty. 
I take a look on it later, however you can just ignore it, it should not do anything except display the message so the user knows that something is hidden.
A restart should also work to get rid of it since the queue not get saved.

**Comment by cimmy01** [comment]
It is persisting over reboots of the computer so Its a weird one for sure.

**Comment by hama3254** [comment]
> It is persisting over reboots of the computer so Its a weird one for sure.

that should not even be possible, even a restart of the application should clear the list, because the "ListBoxList" has no default value.
![grafik](https://user-images.githubusercontent.com/52826614/84823264-5af90c80-b01e-11ea-90ca-7acf4db88401.png)

**Comment by hama3254** [comment]
> 
> 
> > It is persisting over reboots of the computer so Its a weird one for sure.
> 
> that should not even be possible, even a restart of the application should clear the list, because the "ListBoxList" has no default value.
> ![grafik](https://user-images.githubusercontent.com/52826614/84823264-5af90c80-b01e-11ea-90ca-7acf4db88401.png)

it still should not even be possible if you have more informtion you can reopen this issue
