### ISSUE TITLE
Requesting Cli support for automation

### ISSUE THREAD

**Issue by edgehub-cloud** [hama3254/Crunchyroll-Downloader-v3.0#288]
Can we get this pls for linux

**Comment by hama3254** [comment]
The whole downloader is build around the GUI so it would require changes to the core concept and for the personal use for which the downloader is only meant, the current automation in the form of a completed season download should be enough.
The only thing i can offer is the build in webserver interface for the add-ons. How it works can be seen in the code of the add-on: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/tree/master/CRD-addon

**Comment by chaitanyakr** [comment]
> The whole downloader is build around the GUI so it would require changes to the core concept and for the personal use for which the downloader is only meant, the current automation in the form of a completed season download should be enough.
> The only thing i can offer is the build in webserver interface for the add-ons. How it works can be seen in the code of the add-on: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/tree/master/CRD-addon

I think i would be able to use web interface as sending input from cli

**Comment by chaitanyakr** [comment]
Just came here wondering for the same, would it be able to take input at web interface via cli

**Comment by shyim** [comment]
You can use streamlink it works similar but you need to provide the links by own

**Comment by MSI-Toby** [comment]
The easiest way to get to the web interface from CLI is to call the URL from cURL (https://curl.se/). I haven't tried downloaded anything, but I got the interface to run in wine with mono (https://wiki.winehq.org/Mono).

I'm not so good at reading VB, could you show an example URL of how I can call the web interface?

**Comment by hama3254** [comment]
> I'm not so good at reading VB, could you show an example URL of how I can call the web interface?

@MSI-Toby I use a POST request to transfer the data to the downloader, i use `"http://127.0.0.1:" + Port + "/post"`  for that.

There are 4 parameter which get used `HTMLSingle`, `HTMLMass`, `FunimationURL` and `FunimationMass`.

'HTMLSingle' is desingt to process the Crunchyroll html page directly without loading the url in the build-in browser.

'HTMLMass' might be the most useful since the input is the simplest, i already added the `javascript:` to the url to enable the selecting in the add-on so it simply needs a list of urls with `javascript:` as splitting points.
Each url will now get added to the queue.

`FunimationURL` and `FunimationMass` also require `FunimationCookie` as secondary value to work.

`FunimationURL` also directly processes the input url if the downloader is not busy otherwise. 

`FunimationMass` just sets the `FunimationCookie` as global variable and otherwise it is identical with 'HTMLMass'

**Comment by MSI-Toby** [comment]
Thank you very much!

**Comment by edgehub-cloud** [comment]
Thanks I will try this
