### ISSUE TITLE
After downloading the episode, it is taking more than 1 hour to complete the post processing

### ISSUE THREAD

**Issue by orezraey** [hama3254/Crunchyroll-Downloader-v3.0#289]
The episode downloads fast (about 5 minutes), but after that, each episode takes more than 1 hour to complete
These are the settings I am using
![2021-06-07_23-14](https://user-images.githubusercontent.com/49327055/121111958-1eea2900-c7e6-11eb-8b71-afe58bcc9e4c.png)
I don't have a bad computer, so this is probably not the problem. In fact, I wonder if this "problem" is due to some option that I have enabled (image above), to demand a high number of CPU processing, because my CPU is at 100% all the time

**Comment by hama3254** [comment]
You have re-encoding enabled which "takes time and power".
You even use libx264 which is processed from the CPU so it's slower compared to the amf (for AMD GPUs) and nvenc (for Nvidia CPUs).
"preset slow" does also not make it faster and "7000k" means you don't reduce the file size that much since crunchyroll already uses 8000k so "-c copy" would result in that.
You save about 12% storage with the current settings so i would not recommend them.
I personally use "hevc_nvenc" preset slow with 4000k on my RTX 3090 to reduce the file size to ~700MB with a decent speed and no noticable losses.

**Comment by MSI-Toby** [comment]
I use handbrake CLI to convert separately. At the bottom I've included my batch file. If you put the file into a folder named as the starting frame, it will render it to the profile.json settings. This gives you a chance to clip out the opening clips, like the studio into. You can make this in the GUI and export it out. The batch file will ignore any non-numerical folder and remove the original file once it completes successfully.

https://gist.github.com/MSI-Toby/5678ff0bd8d7d7faa366368c119c605f

**Comment by orezraey** [comment]
> 
> 
> You have re-encoding enabled which "takes time and power".
> You even use libx264 which is processed from the CPU so it's slower compared to the amf (for AMD GPUs) and nvenc (for Nvidia CPUs).
> "preset slow" does also not make it faster and "7000k" means you don't reduce the file size that much since crunchyroll already uses 8000k so "-c copy" would result in that.
> You save about 12% storage with the current settings so i would not recommend them.
> I personally use "hevc_nvenc" preset slow with 4000k on my RTX 3090 to reduce the file size to ~700MB with a decent speed and no noticable losses.

Oh, sorry, I was thinking that since the option "I knot that re-encoding the video takes time and power" was disabled, then all the parameters below were ignored. Now I got it :D
