### ISSUE TITLE
help me is the third time I try to download it

### ISSUE THREAD

**Issue by unusualwilly** [hama3254/Crunchyroll-Downloader-v3.0#292]
[SK8 the Infinity Season 1 Episode 9.5 Part #9.5 Crazy Rock JAM.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6639596/SK8.the.Infinity.Season.1.Episode.9.5.Part.9.5.Crazy.Rock.JAM.log)

i'm use the debug version

**Comment by hama3254** [comment]
funimation blocked the access to the video 1 hour after you started downloading, this is usual not an issue since the download should not take longer than the video playback time but in your case it was down to 0.3 times the playback speed.
If you download multiple episode at the same time then try to reduce that number to allow a view downloads be faster.

**Comment by unusualwilly** [comment]
> funimation blocked the access to the video 1 hour after you started downloading, this is usual not an issue since the download should not take longer than the video playback time but in your case it was down to 0.3 times the playback speed.
> If you download multiple episode at the same time then try to reduce that number to allow a view downloads be faster.

Thank you very much I was downloading a total of 4 videos, I will try again sorry for the inconvenience
