### ISSUE TITLE
The download starts and it does not exceed 10 mb downloaded and it is not my internet helps

### ISSUE THREAD

**Issue by unusualwilly** [hama3254/Crunchyroll-Downloader-v3.0#299]
[Miss Kobayashi's Dragon Maid Episode 1 ¡Tohru, la sirvienta más fuerte de la historia! (Bueno, es una dragona).log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6690122/Miss.Kobayashi.s.Dragon.Maid.Episode.1.Tohru.la.sirvienta.mas.fuerte.de.la.historia.Bueno.es.una.dragona.log)

**Comment by hama3254** [comment]
I can't see an error inside the log, it seems like the download process just not responded any further than the 10 MB the downloader displayed in the UI.
This is not an issue from my side since the default download uses a multimedia framework (ffmpeg) but i would have some suggestions.
The first thing I saw is you save the output in drive F: and I assume it's a USB flash drive and I would not recommend to directly choose one of those as output folder.
The second idea would be the use of the `hybrid mode` which caches the streaming files first before the multimedia framework processes it into the final video and accessing local files should make it easier to process.
