### ISSUE TITLE
The download process seems to have crashed

### ISSUE THREAD

**Issue by pcprogamer** [hama3254/Crunchyroll-Downloader-v3.0#304]
Enter your version below, it can be found in the "About" section of the settings.
Version : 3.0

I recently took a look at this to download some episodes off Crunchyroll. When I try to download it says "The download process seems to have crashed" and "Press the play button again to retry". I press the button but it does it again. What should I do.

**Comment by hama3254** [comment]
The reasons the download can crash are to many to give any useful advice without the error log.

The template you used for this issue contained instructions for everything you have to add which makes it possible for me to help.

You also most certainly don't use version 3.0 since it is delete since January 2020 for security issues so please read and follow the instructions.
