### ISSUE TITLE
CDR on Linux

### ISSUE THREAD

**Issue by UnPossible-Me** [hama3254/Crunchyroll-Downloader-v3.0#307]
Hello,
I happened to stumble upon this wonderful project. There are many downloaders out there, but I'd like to commemorate you for keeping this open-source.

Unfortunately, looking throughout the project, I could find no Linux version, so I turned to the issues,
[Issue 62](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/62) and [Issue 5](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/5) were most helpful.

While attempting to re-create your work, I encountered some problems:
1. `dotnet45` fails to install, I've confirmed that it's not an issue on my side. No matter, `dotnet452` installs just fine with I understand is just the next version.
2. More importantly, CRD fails to launch from PlayOnLinux. I don't know what's going on, but I'm including the debug file should it come on any use:
[playonlinux.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6721360/playonlinux.log)

Any Ideas?

**Comment by hama3254** [comment]
I got it to work with `Crunchyroll-Downloader-v3.8-Beta-U10` by using Wine without PlayOnLinux.

i would suggest you use the text version below but here is a recording of my journey https://www.youtube.com/watch?v=oaTuOpcaeAk

I personally followed the Ubuntu  installation guide for Wine since i used a fresh Kubuntu VM for the test.
The guide can found here : https://wiki.winehq.org/Ubuntu but they also have more for other Distros: https://wiki.winehq.org/Download

After that i was not able to run the downloader but i found the solution here : https://askubuntu.com/a/1106750
i followed it and installed `winetricks` with the command `sudo apt-get install winetricks`.
`winetricks` gets used after it has installed to get the .net framework 4.5 running with the command `winetricks dotnet45`

that takes a really long time and requires user input so you need to be patient.

that done i started the `Crunchyroll Downloader.exe` with `wine Crunchyroll\ Downloader.exe` just to get this issue `X Error of failed request:  GLXBadFBConfig` for which i found the solution here https://forum.winehq.org/viewtopic.php?f=8&t=34889 and it's actually pretty simple just execute `export MESA_GL_VERSION_OVERRIDE=4.5` in the terminal and it work after that

**Comment by UnPossible-Me** [comment]
Many thanks for the workaround.
It does seem to _almost_ work.

Whenever I try to download something, I get hit with:
![Error](https://user-images.githubusercontent.com/71452014/123555985-8f151a80-d7a6-11eb-8a9d-30459df5ea4f.png)

That follows with:
![Error2](https://user-images.githubusercontent.com/71452014/123555994-9b00dc80-d7a6-11eb-98c0-6b1f02e308d8.png)

Which completely shuts down the program.

This is the backtrace log it gives:
[backtrace.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6722144/backtrace.txt)
Which... I don't see anything useful except perhaps the ending system information.

**Comment by hama3254** [comment]
i took the liberty to crop the white around the images.

> Whenever I try to download something, I get hit with:
> ![grafik](https://user-images.githubusercontent.com/52826614/123557681-8f0b1f80-d792-11eb-81b9-3d935e0581c2.png)

after a quick online search it seems like that is just a tracking service, so if that is the only issue i would apply a dirty trick an just add the domain `gum.criteo.com` to the `CRD-Domain-Blocklist.txt` that can be found inside the `AdBlock` folder of the downloader, that should terminate the connection from the downloader site and is not unexpected then.

I can not really help much more since i'm not a linux user for exactly that reason i can't get even my own ap to work let alone any games.

**Comment by UnPossible-Me** [comment]
Thanks for making the images a bit better, I have absolutely no idea how to use inkscape.

Blacklisting the domain seems to have fixed the initial problem, the first pop-up no longer appears. 
pears. 
The second one unfortunately still exists. I'll keep messing around with little things, see if I can get it to run. I suspect it has to with my wine version, but we'll see.

I've setup a windows 10 VM for now. I had the same `gum.criteo.com `issue, blacklisting fixed that as well. I can't seem to set the US cookie anymore, I solve the Captcha, continue with Sign In, and once on crunchyroll, the browser just abruptly closes.
But I can still download just fine though , so I'm not complaining.
It seems to work on Windows without a hitch, so I think this'll be my setup for now. :)

**Comment by sl1pkn07** [comment]
is possible build/run throught Mono?

https://www.mono-project.com/

is the more close to native for .net projects

greetings
