### ISSUE TITLE
Would it be possible to select with video container to use?

### ISSUE THREAD

**Issue by Ryahn** [hama3254/Crunchyroll-Downloader-v3.0#31]
Hello, I was wondering if it would be possible to add a feature to switch between using MKV or MP4. I prefer MKV over MP4 due to chaptering, etc

**Comment by hama3254** [comment]
Since Crunchyroll uses mp4 i don't see a benefit to use mkv.
There should be no more functions used by CR then mp4 allows.

**Comment by Ryahn** [comment]
> Since Crunchyroll uses mp4 i don't see a benefit to use mkv.
> There should be no more functions used by CR then mp4 allows.
Oh I thought was in .ts form and not mp4

**Comment by hama3254** [comment]
>
>  Oh I thought was in .ts form and not mp4

the files itself are .ts files but they just splitted .mp4 files as far i can tell. 
i don't see chapters in the m3u8 files and i did not look at the mpd files very much because the m3u8 versions worked better. 

i use the "adaptive_hls" stream from crunchyroll to download the video, but there exist more formats like "adaptive_dash", "vo_adaptive_dash" and "vo_adaptive_hls" but they are all listed as mp4 :
.
"vo_adaptive_hls" (mpd file):
![grafik](https://user-images.githubusercontent.com/52826614/86649623-36230400-bfe2-11ea-8e6d-0b4f08d7e628.png)
"adaptive_dash" (mpd file):
![grafik](https://user-images.githubusercontent.com/52826614/86649740-4fc44b80-bfe2-11ea-96d2-7bca17c36271.png)
"vo_adaptive_hls" (m3u8 file):
![grafik](https://user-images.githubusercontent.com/52826614/86649829-65397580-bfe2-11ea-9aed-3c1b8e2ad8e2.png)
and "adaptive_hls" (m3u8 file and ther one i use to download currently):
![grafik](https://user-images.githubusercontent.com/52826614/86648012-cd875780-bfe0-11ea-8f0c-78d919f62a88.png)

**Comment by Ryahn** [comment]
Ah, learn something new :)

It makes a lot more sense to keep it MP4. I will just convert/encode them to MKV where needed. Thank you for your time.
