### ISSUE TITLE
APP Freezes

### ISSUE THREAD

**Issue by andersonmoura** [hama3254/Crunchyroll-Downloader-v3.0#319]
It's kinda hard to explain, so I recorded.

I'm running it over a remote windows session and as long as i keep the remote session open It works perfectly. If i close the session and reopen it, the app just freezes and i can't clink anywhere or get the log.

It happens in versions v3.8-Ealry-Beta and v3.7.8.6

https://user-images.githubusercontent.com/1872176/125105933-6a2d7b00-e0b5-11eb-97ce-871ed71168d7.mp4

**Comment by hama3254** [comment]
I am more concerned about the calculation issues of the downloader, the first number should be the real downloaded data.

But now to your Problem, which is quite specific.
Simple "solutions" would be either running the Downloader on the machine you are in front of or keep the remote desktop open.
I can not really test it since my server runs Linux so i only tried it for a short time with my phone and my PC and as far i can see it's has something to do with the hybrid mode.
I just have no idea what's happening since windows does not see that as error so the event viewer does not display anything and the app is unresponsive.

**Comment by andersonmoura** [comment]
I'd like to let you know that I have the remote pc plugged to a TV over HDMI. Using it directly this behavior also happens if a switch to another HDMI Input e return to it...

And you're absolutely right about the hybrid mode. I just disabled it and the app stopped to be unresponsive.

ps: thanks by the way.. awesome app

**Comment by hama3254** [comment]
> Using it directly this behavior also happens if a switch to another HDMI Input e return to it...

i never test such things because for one you can use the computer perfectly fine with the download running and that is something i did not even think of because my monitors are only attached to the computer and my server/nas run's on linux so with the 2.5Gbit/s connection i have with the nas downloading on my maschine with the nvidia encoder from my RTX card is the simplest way for me.

and why the freeze happens is something i don't understand especially with just he hybrid mode which does nor run as independent process like the normal ffmpeg download but it run's on an extra thread to keep the UI from unresponsive behavior.

**Comment by hama3254** [comment]
it took some time to find the issue but i think i have it.

Video: 
https://www.youtube.com/watch?v=Foe674ZG3XA

The Download is a CefSharp version called ` Crunchyroll-Downloader-v3.x-Remote_Test.zip` and can be found here: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x

The issue was just the stupid `GeräteID` (eng. Device ID) generator which was in the settings form because it was original used for the US unlock which has been moved to the server so i used that function to get a random temp folder but did not move it to another form or a module.
now i have done that just for a clean up and it worked as seen in the video.

**Comment by momokinou** [comment]
Hi,
I'd like to add that the app crash when windows enter in sleep mode.

**Comment by hama3254** [comment]
> Hi,
> I'd like to add that the app crash when windows enter in sleep mode.

which version did you try? the downloader also should prevent that the computer is going into the sleep mode while it's downloading as seen in #310

**Comment by momokinou** [comment]
Hi,
I'm using the last version.
I think it goes in sleep mode because I use your app in the background, I have all my other apps on top.

Thanks for your response :D

**Comment by hama3254** [comment]
This should be fixed so i close this now.
