### ISSUE TITLE
item to queue ??

### ISSUE THREAD

**Issue by garsbien** [hama3254/Crunchyroll-Downloader-v3.0#341]
Good evening friends, it's normal that I no longer know to download via the software I have the file in the queue ?

<details>
  <summary>images</summary>

![hamacrunchiroll](https://user-images.githubusercontent.com/45321704/128613227-58174588-15ea-4c24-b1bd-970065daa7d3.png)
![hamacrunchiroolltest](https://user-images.githubusercontent.com/45321704/128613228-56a195cb-7a81-4373-af8d-8c84a2f4af4e.png)
  
</details>

this is a small version that I made based on the Hama code here : [removed]

Thx in advance !

**Comment by hama3254** [comment]
it seems like you used the source from github which was not updated during the release of U12 which fixes a major flaw inside the downloader.

i removed the url to the version since it will not work properly and might cause error report that are already fixed.

I also don't support any changed version, i don't know usually what's wrong with my code but i know what it should do so i can check issues.
this however is not the case with modified versions especially without source code.

for a normal version you click on the status text to get into the queue.

**Comment by garsbien** [comment]
i have the same problem with your U12. Does it work for you ? do you have to wait a long time? I have nothing in the bottom bar ?

thx

**Comment by hama3254** [comment]
Just click on the text then the queue is visible, it will then download as soon as the download limit is higher than the download count.
here is an example of that, i already tried to make it more clear to click the text.

https://user-images.githubusercontent.com/52826614/128627595-db569d90-6d43-40f3-be5e-7a05d57ba8df.mp4

**Comment by garsbien** [comment]
always the same issue :'(

**Comment by hama3254** [comment]
> always the same issue :'(

please add some more information what's happening and with what url and make sure there is more than 0 here :
![grafik](https://user-images.githubusercontent.com/52826614/128630472-189bebba-3848-4416-af8e-d26177ebb212.png)

and it would also be helpful if you could write in your native language because i can drop it into a translator for both english and german to get something that is most likely more understandable than your english.

**Comment by garsbien** [comment]
super merci visiblement c'était ça (download simultané était sur 0 lol ) désolé pour mon anglais, sa marche trop content, bonne journée Hama !  t'assure ! Tu peux clore ♥
