### ISSUE TITLE
Download speed

### ISSUE THREAD

**Issue by momokinou** [hama3254/Crunchyroll-Downloader-v3.0#353]
Hi,

I hope you're doing great.

I use your app at least 8 hours a day and I thank you for the help it gives me to download ALL of crunchyroll :D
Here's a preview of what i have downloaded so far:
![image](https://user-images.githubusercontent.com/31689903/130217077-36b73826-63bd-4276-a343-3720f429d864.png)

But I have noticed problems with the download speed.

I have episodes that download at 50MB/s if not more and others that download at less than 1MB/s.

Here's a speedtest of my connection to prove that I have enough speed:
![image](https://user-images.githubusercontent.com/31689903/130216737-6299c5af-0c01-49be-87ba-88cca68c3a9a.png)

Here's an example of slow download:
![image](https://user-images.githubusercontent.com/31689903/130216863-af5c907f-292a-4fd8-9802-975376e422a0.png)

If you need more informations, just let me know.

**Comment by hama3254** [comment]
There are many things that influence the download speed.
It starts at your CPU, the Hybrid Mode uses multiple threads and i decided that half of the `Logical cores` is a fine amount per download (based on my 9900k with 16 `Logical cores` and just 8 `Physical cores`).
That should make a CPU with more cores better.

Then we need to take a look at your internet, it looks like gigabit fiber to me so it should be fine.

The problem is that your connection is not everything, the server needs a good connection too and everything in between needs to work fine. 
On that we have no influence that why you see the bandwidth drop from 50MB/s to 1MB/s.
I also have already seen that as example Episode 4 from `RWBY` Season 2 downloaded faster than Episode 4.5 even tho the file size is multiple times lager since Episode 4.5 ist just a 2:16 min addition to the show.

**Comment by momokinou** [comment]
Thanks for your response,
Okay, i'll try the hybrid mode when i'll receive my new HDD, you just filled 10To on my current one x)

Anyway, thanks for your hard work, i'll keep on using your program :D
Have a good day.
