### ISSUE TITLE
Crunchyroll-Downloader

### ISSUE THREAD

**Issue by joeldark2015** [hama3254/Crunchyroll-Downloader-v3.0#354]
Hello friend, hama3254 I am a follower of yours, because I come to inform you that crunchyroll updated its entire platform, and the crunchyroll-downloader program apparently stopped working, I wonder will you continue updating this beautiful project.

**Comment by hama3254** [comment]
I guess you are referring to the beta website, that version is already supported since [v3.8-Beta](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta) and is also working in the [new Chromium versions.](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)
If you have a issue please describe exactly what happens with which Url, but please check first if you are allowed to access the episode inside the build in webbrowser.
Common issues there are that you might need to login (for premium episodes or the beta site all together) or that your browser has a VPN add-on which the downloader does not has.
