### ISSUE TITLE
New crominum-hotfix is able to login funimation but fail to download video[also after +url paste](shows protected content)

### ISSUE THREAD

**Issue by devanshkasotia** [hama3254/Crunchyroll-Downloader-v3.0#371]
I using this new hotfix individually in new folder
(I saw in game that hotfix is file that paste in existing folder for solving error)--we have to do paste this hotfix in some version?

SOLVE THIS!

**Comment by pruebark9** [comment]
Hi, I am having a similar problem since 2 hours ago. When downloading something either by putting the direct link or changing to /es/shows in all versions that are available in Chromium, vrv, U13, 357_2, 357_5 in all I get the same error when I try to download from Funimation with Spanish dubbing.

https://i.imgur.com/Ybg0NlP.png

**Comment by hama3254** [comment]
Version [Crunchyroll-Downloader-Chromium-U5](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases) as been uploaded if there are more issues please use #373
