### ISSUE TITLE
Sometimes missing frames and sometimes audio not tracking the video

### ISSUE THREAD

**Issue by proall** [hama3254/Crunchyroll-Downloader-v3.0#387]
Hi,
I tried every latest bugfix and stable version in this project, i don't know why, maybe i am the only one that having this problems..
But when i'm using hybrid mode / standard mode its changing the CRC-32 code, and sometimes the file size is 1.34xxxxxx
And sometimes it is 1.47xxxxxx and sometimes even less than 1.2xxxxxx (changing the size every download (the same episode)) , thats fine? That need to be like that? Its not a problem? I tried someone's else script and the CRC-32 not changing and keeping the same bytes.
Maybe you can add a normal downloading for download perfectly batch, without any errors or something?

**Comment by proall** [comment]
Maybe its becuz of my win11?

**Comment by proall** [comment]
PROBLEM SOLVED,
The problem was the subs merge, also i'm using the new U7 version, maybe that too.

**Comment by hama3254** [comment]
If you have any issues with the output file then you can check the process log on each download by right clicking it's entry inside the download and than save the log to file or copy it to the clipboard.

It can happen that parts are missing for a video due to any kind of network issue, the hybrid mode try's to redownload failed parts but this does not work always and ffmpeg just continues.
I added the option to detect error for that, it can be found on the Main settings Page at the bottom.
