### ISSUE TITLE
Funimation Issue Only Subtitle

### ISSUE THREAD

**Issue by kanohn** [hama3254/Crunchyroll-Downloader-v3.0#391]
Hello,

If we set to download only subtitle for all episodes of a show, some subs said that downloaded succesfully but it doesn't appear on the folder, just a few subtitles, not all..

For example:
https://www.funimation.com/shows/mieruko-chan/?qid=

I try to download all only subtitle of this show, but only subs from eps 4,5,6 appears for me..

I'm using version U8

**Comment by hama3254** [comment]
i guess i have to remove the `dfxp` format but other than that it seems to work fine.
**![grafik](https://user-images.githubusercontent.com/52826614/140786946-c16c2954-2fc1-40d2-b1ce-c7750f17d172.png)**

**Comment by kanohn** [comment]
what do you mean? Well this thing don't happen all time, but its very common for me, i will print next time

**Comment by kanohn** [comment]
Look, i don't know whats going on, but its bug for me all time now..
https://postimg.cc/gnvjKRRc

**Comment by hama3254** [comment]
i removed the log since it contains the request headers which have an access token from the account in them.

i uploaded a test version for you with a different logging, there where no data from the subtitles in the older version so added it and i  removed that access token issue.
[Crunchyroll-Downloader-Chromium-391.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)

**Comment by kanohn** [comment]
Thanks.

I have tested with the version 391, same show. I have setup again to download all 6 episodes, but only downloaded 3 subs in "Only subtitle mode" Here are the log:

https://pastebin.com/KbV8HBuE

**Comment by hama3254** [comment]
It seems like the data from Funimation is changing.
Since the new API they have a `primary` video and `fallback` videos.
The log indicates that the first 3 episodes have as primary audio language `pt` while the last 3 have `ja`.
I take a look at this with a Brazil VPN instead of the US i usually use later.

**Comment by hama3254** [comment]
The data from funimation change based on the dub language inside the account settings.
I also don't get any subtitles with that inside there player, however there are in the fallback available i just need to add them.
![grafik](https://user-images.githubusercontent.com/52826614/141337401-dbf8267e-f4f0-4958-b6bd-f93bf45b3953.png)

This might take some time since i still need to finish with my new computer setup but it should work for you to use Japanese as dub setting 
![grafik](https://user-images.githubusercontent.com/52826614/141337838-0d6f62a5-9080-440b-a7ca-bc3b5624a5b5.png)

**Comment by kanohn** [comment]
Thanks!
