### ISSUE TITLE
Episodes aren't getting put in season folder

### ISSUE THREAD

**Issue by Carlost2024** [hama3254/Crunchyroll-Downloader-v3.0#395]
When I download episodes from a series with more than one season it used to create a folder for that season with the episodes in it.
Also the temp files folders aren't deleted by themselves anymore.
If I remember correctly there was a little box asking me something about the temp files and I stupidly clicked yes.
I don't know how to revert this.
Can you please help me.

Thanks in advance

**Comment by hama3254** [comment]
You can disable and re-enable the hybrid mode to get the prompt again.
For the season please check if you select subfolder for the anime or Anime and season.
If it was selected correctly then i need the website you download from (funimation, Anime on demand, crunchyroll or crunchyroll beta) since there have all there unique code.

**Comment by Carlost2024** [comment]
Thanks the fix with the prompt worked like a charm.
Im selecting anime and season for crunchyroll normal not the beta

**Comment by Carlost2024** [comment]
Tested the season feature at a diffrent anime and it works.
Probably just was a problem with a special one (Name: Strange+)

**Comment by hama3254** [comment]
@Carlost2024 the reason is that nighter of the two Seasons (?) is tagged with any season at all.
![grafik](https://user-images.githubusercontent.com/52826614/141828617-755cbeae-03e1-4519-ab62-89ba3c64c9d8.png)
![grafik](https://user-images.githubusercontent.com/52826614/141828646-655b6292-83e6-4621-a492-b1607816ad92.png)

This is how the downloader expects it.
![grafik](https://user-images.githubusercontent.com/52826614/141828673-7ea6c63e-c930-4458-9d7a-aeff4342b6b5.png)

**Comment by Carlost2024** [comment]
Ok so it's just a crunchyroll numbering/naming issue.
I checked the series on tmdb and it was the first and second season.

Thanks again for the quick help
