### ISSUE TITLE
Funimation, impossible to download subtitles separately

### ISSUE THREAD

**Issue by Olly0225** [hama3254/Crunchyroll-Downloader-v3.0#403]
Hi, when I try to download the Subs only from Funimation I get the following error:
(https://user-images.githubusercontent.com/95555265/144731568-179e1507-5c3e-4818-bd94-70ea97e31e23.PNG)

I'm using the V3.8.0.9 Chromium-U9.3 version.

Any ideas?

**Comment by hama3254** [comment]
I'm i the middle of massive changes (complete code clean up and removing anime-on-demand.de due to it's shutdown) so i won't be able to release a fix this year, i can suggest three workarounds.
All workarounds only work merged subs disabled!

Use 360p to download a just a small video which can be deleted.

Cancel the download after it has started (subs are downloaded right at the begin).

Or break the download function with invalid settings, select an encoder you don't have for me any `amf` will fail since they are for AMD Graphic Cards and i have an Nvidia one.
This requires the disable of the Hybride mode.

![grafik](https://user-images.githubusercontent.com/52826614/144745477-c87f9c51-2b28-4e56-8941-f1a2a987294b.png)
