### ISSUE TITLE
Funimation Download its broken Please Fix IT :c

### ISSUE THREAD

**Issue by lgwenl** [hama3254/Crunchyroll-Downloader-v3.0#407]
Used version Crunchyroll-Downloader-Chromium-U9.3
When I try to download chapters from funimation with a premium account, the program asks me to log in to the internal browser of the downloader, but I have to enter the browser to download each chapter, it does not do so automatically even after having logged in to the internal browser.
Besides that, when it shows the chapter to download in the browser it says "sorry, there has been a problem with the video" and I need to close the browser so that the program picks up the link and so it is with each chapter.

**Comment by hama3254** [comment]
You just need the webbrowser once to login which gives me the access to the cookie for the session.
To add videos you don't need to open the browser, you need to use the `Add Video` window which open with the `+` icon on the top left.
There you do the download by either using a direct link to an episode which should download the episode or you use the overview page of the anime which gives you a season/episode selection for "start at" "until there" menu.

**Comment by lgwenl** [comment]
![image](https://user-images.githubusercontent.com/80654164/146652199-2c9c67aa-309a-4119-927f-956bbee84319.png)
![image](https://user-images.githubusercontent.com/80654164/146652236-28b82f5c-8bcd-407e-ab38-f11a418e89dc.png)

If I do not enter the internal browser of the program, do not download anything, it does not start anything and the only thing it says is "loading in in the search engine" but it does not start any download. I have to enter the internal browser and it shows this error in the browser and does not continue searching the video or anything, then I have to close the browser and there it starts to download the chapter but after the third or fourth time it doesn't work anymore.

**Comment by hama3254** [comment]
I had a closer look at this issue and added a bypass with [Crunchyroll-Downloader-Chromium-U10](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x) because it seems they changed there video loading and now i get most of the time `VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. [object Object]` which makes sense since the build-in browser does not support `h264` which is what funimation uses. 
![grafik](https://user-images.githubusercontent.com/52826614/146675359-f7dc3cca-f6c5-4407-9498-1fcb212fa089.png)

i added a direct call to the api which i usually got from the traffic and i was not sure that it stays the same since `d33et77evd9bgg.cloudfront.net` looks random to me, that is why if that fails it should use the old method with the browser.

**Comment by janilssonn** [comment]
I have a problem, the queue doesn't work on Funimation the video downloads but the link doesn't disappear, it keeps trying to download the same video all the time. Until you delete the link from the queue.

**Comment by janilssonn** [comment]
![image](https://user-images.githubusercontent.com/16007846/146688792-af5f7a09-2e3f-4e97-b1a0-d438edffd516.png)

**Comment by lgwenl** [comment]
![image](https://user-images.githubusercontent.com/80654164/146689470-457a7b56-ab2e-42ab-a4b4-dc3885d568d9.png)

In the new version of the program the funimation error still appears but at least it gives the links to the downloader the new problem is that now it infinitely download the second chapter (at least in my case), and when this does not happen by giving the option - status: items in queue click me to work off- the program just stops responding.
I mean, if one thing doesn't happen, the other happens please fix it :D

**Comment by hama3254** [comment]
the issue should be fixed with [`Crunchyroll-Downloader-Chromium-U10.1`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)
