### ISSUE TITLE
Funimation download speed

### ISSUE THREAD

**Issue by kanohn** [hama3254/Crunchyroll-Downloader-v3.0#421]
Funimation download speed is very slow on my end..

while i get 18mbps on crunchyroll videos, on fumination keeps varying between 0.5mbps and 1mbps..

could i do something to speed up downloading from funimation? thank you.

**Comment by hama3254** [comment]
Funimation was always slower for me which is likely because of my VPN that i need because i am from Europe.
The only way of improving it would be to use the `Hybrid Mode` to ensure some level of multitasking based on your Hardware.

>the Hybrid Mode uses multiple threads and i decided that half of the Logical cores is a fine amount per download (based on my 9900k with 16 Logical cores and just 8 Physical cores).

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/353#issuecomment-902699544_
