### ISSUE TITLE
Error downloading with updated ffmpeg

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#424]
I have tried to update ffmpeg, same contributor as the one you use (gyan).

It works with 4.4.1 but not with 5.0.

Can you please try it?

**Comment by hama3254** [comment]
ffmpeg changed the `user-agent` option to `user_agent`.
Older versions only throw a notification `The "user-agent" option is deprecated: use the "user_agent" option instead` 
5.0 has now removed the support for that and you get a crash :

```
Unrecognized` option 'user-agent'.
Error splitting the argument list: Option not found
```

**Comment by tormento** [comment]
@hama3254 can you fix it and include in the next "long path" release?

**Comment by hama3254** [comment]
i don't plan to upadte the downloader to ffmpeg 5.0 for now.
for the short test i changed it and since it should work with the older version anyway i just keep it, if you want to change your ffmpeg version you can do that but there will no support from my side since the time it takes to check every possible combination of commands the downloader can genarate is a little high (with hybride mode, merged subs and re-encoding).
[if you want you can try the latest debug version directly from the repository](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/blob/master/Crunchyroll%20Downloader/bin/x64/Debug/Crunchyroll%20Downloader.exe) just get it and replace your existing `Crunchyroll Downloader.exe`.
i also removed the debug message that pops up if the path is longer than 256 chracters.
