### ISSUE TITLE
Define subtitle file naming

### ISSUE THREAD

**Issue by inter5tella** [hama3254/Crunchyroll-Downloader-v3.0#426]
**Is your feature request related to a problem? Please describe.**
The default subtitle file naming is not working for all common encoding applications. Some of them do require a specific naming to get recognized.

**Describe the solution you'd like**
Instead of naming the subtitle files in their native language, it should be possible to name them in ISO639-1, ISO639-2, and English. i.e. Deutsch should be named as 'German'.

**Describe alternatives you've considered**
An alternative would be to define a hard-coded language code (or template) for the preferred encoding software.

**Additional context**
This has been tested on Staxrip, where 'xxxxxx.Deutsch.ass' was not being recognized, but 'xxxxx.German.ass' was indicated in Staxrip to define the subtitle file to the language of German.

**Comment by hama3254** [comment]
i already use the `ISO639-2` for the "merge subs" option but i can find a ISO Code for `Español (Latin America)` so i use the same as for `Español (España)`  which was ok for that because i can add titles for the merged subs.

<details>
  <summary>Images</summary>
  
![grafik](https://user-images.githubusercontent.com/52826614/150682047-1fc613e0-a7c4-496d-8ee2-4f4a6472efb8.png)
![grafik](https://user-images.githubusercontent.com/52826614/150680981-2fa47df5-ceea-427f-ac80-1a2f9c249afd.png)

  
</details>

so i did it like that with the option to use either option or both. 
![grafik](https://user-images.githubusercontent.com/52826614/150682168-e4c84107-b0ba-4e96-9b97-cdbbcfc8a75a.png)

**Comment by inter5tella** [comment]
Hi hama,
thanks for your reply.

Is the last screenshot of you made from an already existing CR version or is it a POC?

**Comment by hama3254** [comment]
> Is the last screenshot of you made from an already existing CR version or is it a POC?

i just finished the release [you can find it here](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x) but it is somewhat untested especially for funimation.

**Comment by inter5tella** [comment]
I've tested U12 and is working well so far. But is it also possible to output the Crunchyroll subtitle file naming in English instead of its native language? i.e. output _German_ instead of _Deutsch_.
I guess by that, every possible scenario is covered depending on which encoding software is used by the user and how they recognize the subtitle's language.

**Comment by hama3254** [comment]
That would be possible but the option is already only useful for just a minority at best so there would be close to no point to add that.
