### ISSUE TITLE
Merge VO & Dubbed version ?

### ISSUE THREAD

**Issue by fo-enyx** [hama3254/Crunchyroll-Downloader-v3.0#437]
Hello, 
It is possible to merge audio from Dubbed versions with VO versions with subs programmatically ?

Best,

**Comment by hama3254** [comment]
I assume that `VO` means the original Japanese dub?
I also assume that you talk about Funimation since for crunchyroll this is not going to happen with there mess of individual Dub/Sub seasons....
![Screenshot_20220214-065547](https://user-images.githubusercontent.com/52826614/153808105-310a0dfd-b05c-4ad9-a774-28ac757a4004.png)

For Funimation it would be technically possible since they even have separate Audio and only soft subs but i don't know if many would want that and it would cause more trouble since some dubs are free while other might require premium and it could be a mess.

**Comment by fo-enyx** [comment]
No, I talked about CR because i'm french ;(,
Yeah, VO is Japanese Dub, 

I would like to fuse programmaticaly Jap Dub, VF, Dub and subs to do a MULTI dubs/subs file output, without editing after with mkvtoolnix.

Idea would be to get dub from jap + dub from vf + subs and have only one output file.

But I don't know if timecode are the same, sadly, but I hope it's the case.

**Comment by hama3254** [comment]
It is simply not possible to even know if `Anime X` has a Dub for `Language Y` let alone connecting the existing ones.
You only way is to download the Episodes with softsubs and then add the french audio stream from a seperate downlaod with any tool you want.

**Comment by fo-enyx** [comment]
Sadly,
Thanks a lot,
I guess it is possible but not in a consistent way to do it programmatically :(

**Comment by LTech77** [comment]
The Post might be older, but I made my self a little Excel script with some Batch files and mkvtoolnix to do this somewhat semi-automatically. With this, I can merge Ger Dub and Jap Dub + Subtitles together with only 1 Video stream. You need to make sure tho that the two are compatible beforehand. With this it takes me about 5 min to prepare, and the rest is done automatically.
