### ISSUE TITLE
Funimation videos no longer downloading

### ISSUE THREAD

**Issue by Priception** [hama3254/Crunchyroll-Downloader-v3.0#438]
When downloading any of Funimation videos the software is unable to find the video and throws an error. 

I tested this on both new epsiodes (for example Episode 76 of Attack on Titan) as well as Funimations much older videos (A Certain Scientific Railgun S1 Ep1) and both come back with the same error.

![image](https://user-images.githubusercontent.com/50168181/155013313-78091183-4b35-4a48-bfc3-33e4b8522694.png)

**Comment by hama3254** [comment]
`A Certain Scientific Railgun S1 Ep1` works fine for me and for `Episode 76 of Attack on Titan` would be the simple explanation that it requires an account due to `mature content`.
Login inside the build in webbrowser and try the episodes again.
![grafik](https://user-images.githubusercontent.com/52826614/155022953-45342872-3dce-4f1b-86bf-70160e1a7025.png)
![grafik](https://user-images.githubusercontent.com/52826614/155022978-50faecf1-5dd1-4005-90eb-baf81240c8da.png)

**Comment by Priception** [comment]
Hi, sorry I found out the issue was that I wasn't signed in on the Crunchyroll Downloader Browser and was not able to download the video because it was locked behind "Premium"

Downloads are working now.
