### ISSUE TITLE
Temp directory

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#449]
To distribute wearing out on different SSDs and to increase reconstruction speed, I'd like to have the possibility to define a different temporary directory for the chunks in hybrid mode, other than the download one.

**Comment by hama3254** [comment]
Adding the option is no problem even to i believe that the SSD wear is not that big of an issue but better save than sorry.
And for the speed I'm not sure if it will improve since I use re-encoding but you can give it a shot after i find some time to get to implement it.
If you want to go completely overboard a separate temp folder would even allow easy use of a RAM Disk to further eliminate SSD wear.

**Comment by hama3254** [comment]
It was surprisingly easy to add.
[feel free to test Crunchyroll-Downloader-Chromium-U13 and if you find any issue i keep this thread open](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)
![grafik](https://user-images.githubusercontent.com/52826614/159118423-c645dca5-91b2-488c-acdc-5adfa338e655.png)

**Comment by tormento** [comment]
Great! I will test ASAP.

P.S: So you are German!

**Comment by hama3254** [comment]
with no issues so far it seems to work fine so i close this now.
