### ISSUE TITLE
Add Support

### ISSUE THREAD

**Issue by Achu2234** [hama3254/Crunchyroll-Downloader-v3.0#451]
Add Support for  Batch Dl for Completed Animes 
remove queqe feauture so we can dl anime episodes fastly without waiting other epi to complete
Add verfast in FFmpeg option

thank you

**Comment by hama3254** [comment]
> Add Support for Batch Dl for Completed Animes

it's already possible to download a whole season if you use the Anime page instead of an direct episode.

> remove queqe feauture so we can dl anime episodes fastly without waiting other epi to complete

you can do up to 12 epidoes at the same time that should be more than enough with re-encoding.

> Add verfast in FFmpeg option

This project is a Downloader not an converter tool so i want to keep it simple.
If you want more control over the Video file than i suggest using the default `-c copy` and then use either ffmpeg yourself or any other converter

**Comment by Achu2234** [comment]
ok sir but 
**### 

> it's already possible to download a whole season if you use the Anime page instead of an direct episode.

**

i tried but no optoin
