### ISSUE TITLE
Episode checklist

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#452]
Sometimes I have to download some non consecutive episodes from different seasons.

Instead of a pulldown menu, could you try to create a checklist with the episodes, divided by seasons, being able to select all or just some? Calling the download list multiple times can sometimes be really tedious.

**Comment by hama3254** [comment]
the simplest solution would be to use the add-on for your webbrowser.
[As can be seen here](https://github.com/hama3254/CRD-add-on/discussions/1) you can select episodes and just pass them to the dowload queue with a view clicks.
A proper tuturial is not avalible anymore due to DMCA takedowns so some links are dead but the add-on support just need to be enabled and then the port need to be enterd into the add-on. 
![grafik](https://user-images.githubusercontent.com/52826614/159576997-d854147f-0276-45b0-a9e1-f22737bbe2e9.png)
![grafik](https://user-images.githubusercontent.com/52826614/159577137-d34d1b33-59e8-4d71-b89a-f29594acae20.png)
