### ISSUE TITLE
Replace invalid characters in path

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#453]
I have tried to download Sing yesterday for me and the season name is SING \

Consequently, I have the following error when trying to download with [automatic by Series and Season] on:

![image](https://user-images.githubusercontent.com/2351785/159890347-ad06e367-7b8e-4b02-b1e0-2ae0cd6a7c93.png)

Please replace the invalid character or simply make the downloader ignore them.

**Comment by hama3254** [comment]
The backslash sould not be a problem, i assume that the `"` frome the `"season_title":"SING \"YESTERDAY\" FOR ME",` are the real issues.
Both are valid characters for a path since both have a purpose (at least for windows).
The backslash `\` usually marks an subfolder so this might cause some unwanted subfolders but it should work.
The real issue should be `"` since it is allowed at the start and at the end for windows paths for the case it has a space character within it so it is not directly invalid and is not filtered.

I try add a rule to get rid of JSON excepted Charakters.
