### ISSUE TITLE
Error trying to download

### ISSUE THREAD

**Issue by fis60** [hama3254/Crunchyroll-Downloader-v3.0#474]
Hello,

After updating to latest version am getting this error

Please make sure that the URL is correct or check if the Anime is
available in your country,

But when i tap the Download button again it works the only downside is when trying to download full Tv-Show the error interrupt the process and it can't be downloaded unless i add the episodes one by one.

Using Crunchyroll non beta website.

Thanks

**Comment by hama3254** [comment]
please check what Crunchyroll gives you for the first try, for that open the build in webbrowser (second button from the top left) and then just add the episode normaly.
if the error appears please share a screenshot of the browser.

**Comment by fis60** [comment]
i just deleted the profile folder and logged in again, first try it gave me the error then i couldn't reproduce after sometime i think it comes up again
<img width="764" alt="Screen Shot 2022-05-04 at 7 22 48 PM" src="https://user-images.githubusercontent.com/14325487/166728139-c26bbc7f-697f-4c67-b104-b71e8cbec805.png">
<img width="1421" alt="Screen Shot 2022-05-04 at 7 24 16 PM" src="https://user-images.githubusercontent.com/14325487/166728165-96dcb5ba-ee48-47f9-8d39-65ae864a694a.png">

**Comment by hama3254** [comment]
from the screenshot it looks fine but the error message suggest that [none of the three conditions for a valid site](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/blob/7893afa1de4cb8eee23de3cbe38936f8a6a26296/Crunchyroll%20Downloader/Main.vb#L4367) have been fulfilled.

in the end i can not tell what data the downloader was processing but you should have a `html.log` insider your crunchyroll downloader folder which should contain the raw html the downloader was processing.
i would need that because i can not reproduce the issue myself.
