### ISSUE TITLE
Add download without burn in subtitles

### ISSUE THREAD

**Issue by MSI-Toby** [hama3254/Crunchyroll-Downloader-v3.0#49]
Hi, is it possible to make it so it downloads the video without the subtitles burned in, please?

**Comment by hama3254** [comment]
This is already in the downloader for Crunchyroll.
The "Hardsub language" sets the language for the burned in subtitle.
For Funimation i need to re-encode the video to burn the softsubs into the video stream, i think i can add this with the next version since i need anyway to split apart the settings from Crunchyroll and Funimation into new  groups

**Comment by MSI-Toby** [comment]
I can't believe I never noticed that before! Thanks for all the good work!

**Comment by hama3254** [comment]
> For Funimation i need to re-encode the video to burn the softsubs into the video stream, i think i can add this with the next version

this has been added with v3.5 so i close this now
