### ISSUE TITLE
If title has a : (colon) then it does not auto create series/season folders even when selected

### ISSUE THREAD

**Issue by shinji257** [hama3254/Crunchyroll-Downloader-v3.0#494]
**Describe the bug**
The automatic creation/use of Series/Season folders are not used even if the option is chosen.  Instead it acts like it is set to ignore the subfolder when there is a colon in the series title.  Filenames seem to correctly strip the colon though and are formatted as expected.

**Where does the issue happen?**
 - Platform: Windows 11
 - Settings: Softsubs English, No hardsubs, default ffmpeg, Automatic Series/Season folders
 - Version: 3.8.8.1

**Screenshots**

**Additional context**
For now I'm just creating those folders manually and putting them where I expect them to.  It's more of an annoyance than anything right now.

**Comment by hama3254** [comment]
The main issue is that `:` needs to be a valid character for the path since Windows always uses somthing like `C:\` for drives but everywhere else it is just invalid.

I also already changed the CR-Beta code to remove it before it gets processed.

For the issue itself please stick to [the style of your last issue](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/486) the template has ` - Platform: [e.g. Crunchyroll Beta, Cruchyroll Classic, Funimation]` for a reason since they are 3 different functions and i need to know where to test like in this case Cruchyroll Classic and Funimation worked fine.

**Comment by shinji257** [comment]
Oops.  My brain must have in a different mode at the time.  I'll try to remind myself next time I open a bug.  Thank you for fixing it.

**Comment by hama3254** [comment]
fixed with [v3.8.9](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8.9)
