### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by 2468-13579** [hama3254/Crunchyroll-Downloader-v3.0#5]
Could you please make a linux version if it is not to hard to do?

**Comment by hama3254** [comment]
i had in the past sucsess with running the downloader in Wine with "PlayOnLinux".
Unfortunately i don't remember what i did and all try's today with a new start failed.
and with the old backup from August i got the latest Verison (with small changes) to run but i can not tell if the bad performance is because of the VM i use or if it the programm itself.
Video from my successful try:
https://www.youtube.com/watch?v=hWbJdYLyUzM

Version i used :
https://mega.nz/#!tMthESiS!HPSJCJMpM7xnlTdjcdNMilg89iUbWLOjAClaxALRDbA

**Comment by 2468-13579** [comment]
Thanks a lot! When I tried the normal version in wine it had the same problems as yours in the video, but now it works flawlessly.
