### ISSUE TITLE
Cannot download just 1 file

### ISSUE THREAD

**Issue by ProtocolNebula** [hama3254/Crunchyroll-Downloader-v3.0#502]
**Describe the bug**
When the app ask which episodes do you wanna download (2 dropdowns appear), if you only choose one file and press "download", there is no feedback and the download never start.

**Where does the issue happen?**
 - Platform: Any
 - Settings: Any
 - Version: 3.8.8.1

**Comment by hama3254** [comment]
> This is a very bad UX, you should only need to select the 1rst selector, anyways, this do the trick.

> it's a waste of time if you need to downlaod more than 6 chapters

This is a minor inconvenience at best.

> I'm unable to do a build 
> I've installed the metro framework (which should be marked as dependency), but it still getting me some errors.

I use a modified version of the [metro framework ](https://github.com/hama3254/metroframework-modern-ui) and you might also miss the [RequestHandler](https://github.com/hama3254/RequestHandler)

**Comment by ProtocolNebula** [comment]
Thanks, I'll try to install with it and check if the component that I guess fit best works.

You'll accept the MR if it's fine for the UX improvement?

**Comment by hama3254** [comment]
i finished the latest changes and made a release ([v3.8.9](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8.9)) which also includes the the change to fill out the bottom two drop downs with the first and last episode of the Anime.
This should help with the intended design of the multi download feature to get an entire season at once.

I can not think of a better solution but if you have one i am in general open for ideas but i would like to point out another available way to add downloads would be [the add-on](https://github.com/hama3254/CRD-add-on/discussions/1) which is hard to find since CR send a takedown notice to YT and Mozilla.

**Comment by ProtocolNebula** [comment]
For me it's fine with the "add one" for chrome, so this issue can be closed except @hama3254 do you want to change this behavior.
