### ISSUE TITLE
Hi im new with this type off thing

### ISSUE THREAD

**Issue by ADHD9000** [hama3254/Crunchyroll-Downloader-v3.0#521]
Im sorry to bother you but i don't know how to download the program.
Sorry for asking.

**Comment by hama3254** [comment]
The download can be found on the GitHub [Release page](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases).
I would suggest to use the latest version wich is currently the [Crunchyroll-Downloader-Snapshot](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Snapshot) because i did not had the time for a proper relese at the time.
The final download can always be found inside the `Assets ` which is usually a zip folder that just need to be upacked 
![grafik](https://user-images.githubusercontent.com/52826614/185091972-00a4801f-443a-4c80-9743-1eaec0a0f530.png)

after that the main executable is the `Crunchyroll Downloader.exe`
![grafik](https://user-images.githubusercontent.com/52826614/185092210-bd0a2ed7-5517-42d1-8b64-dbf2e804d231.png)

**Comment by ADHD9000** [comment]
thank you verry much i had the other one that one had no donwload.exe
