### ISSUE TITLE
Downloads in queue

### ISSUE THREAD

**Issue by Kakerayed** [hama3254/Crunchyroll-Downloader-v3.0#529]
Hello. A doubt. When I try download an episode of an anime with "3.8.9 test" version I get a notice at the bottom ("Status: items in queue, click me to work off") 
![r-2](https://user-images.githubusercontent.com/112727493/190675869-9d498bea-ed0e-4cf6-9787-ab2988c6ac1f.PNG)
and other in the principal window at the top that says "Status: 1 downloads in queue". 
![r-1](https://user-images.githubusercontent.com/112727493/190675902-8f5c8778-6d1f-4608-a7bb-ee8eed8cfe9a.PNG)
 Is there any solution?

**Comment by hama3254** [comment]
This is due to the queue feature, if downloads get added from either the add-on or if you add a download while the limit from the settings is reached then it will be moved to the queue.
You can enter the queue from the `Add Video` window with a click on the status text.
The limit would be that option.
![grafik](https://user-images.githubusercontent.com/52826614/190733657-84abb7a2-f24b-413f-88c4-21efe9a28444.png)

**Comment by Kakerayed** [comment]
oh i get it. i had the setting set to 0. thanks

**Comment by Kakerayed** [comment]
thanks
