### ISSUE TITLE
Not showing all seasons

### ISSUE THREAD

**Issue by eioweiow** [hama3254/Crunchyroll-Downloader-v3.0#530]
Description:
When i try to download Danmachi, there aren't showed all the seasons

Where;
Crunchyroll

Screenshoot
![image](https://user-images.githubusercontent.com/113898007/190994009-bd644802-98a8-46fd-901a-317cb2612ae6.png)

**Comment by hama3254** [comment]
The downloader can only process data that Crunchyroll provides.
If there are entire seasons missing then CR does not allow the downloader the access, the reason is usually geo-blocking.
Please check your Webbrowser and see if there is everything available for you without any VPN add-ons inside the browser.

**Comment by eioweiow** [comment]
When i tryed 2 days ago: I was using a VPN to Canada and when i check the browser i could watch first, second, and third seasons. When i logged in, the interface have changed to 'beta', then i could watch second, third and fourth. Today, when i have tryied (without logging) I couldn't whatch first season. Then i think the license has expired.

I undestand that this is not a downloader problem. 

But what i try to explain is: I think the downloader only gets the beta's page info. I understand that if when i am logged in the app browser, the info is getted by the beta (because be logged redirect to beta), but when i'm not logged the info should be gotten from standard crunchy.  No?

**Comment by hama3254** [comment]
> But what i try to explain is: I think the downloader only gets the beta's page info. I understand that if when i am logged in the app browser, the info is getted by the beta (because be logged redirect to beta), but when i'm not logged the info should be gotten from standard crunchy. No?

if you are logged in inside the build-in webbrowser with an beta account then both the old and new urls will access the same page since CR redirects you.
if you are not logged in beta urls simply don't work since you only get redirected to the classic home page and old urls should work as long they are not premium episodes that would require an account.

**Comment by eioweiow** [comment]
Okay, i had tryed yesterday and it worked, thank you. Really good job with this app man ^^
