### ISSUE TITLE
Can you add support for downloading multiple audio tracks and muxing into the same file

### ISSUE THREAD

**Issue by Dijitul1029** [hama3254/Crunchyroll-Downloader-v3.0#538]
As the title says, I would love the functionality of being able to select two or more audio tracks for muxing into the mp4 or mkv container.

**Comment by hama3254** [comment]
As already mentioned inside issue #488 Crunchyroll uses different seasons for differnt dubs.

![grafik](https://user-images.githubusercontent.com/52826614/193555017-023495e7-a497-4c0b-9551-3a551036fd3d.png)

This is not impossible anymore since now seasons match unlike a view month ago where that all have been season 1 with wrong tags.

![grafik](https://user-images.githubusercontent.com/52826614/193555298-180a37b5-a267-461a-953b-ea47c75ff14a.png)


It still is a lot trouble for not much gain, you can easily just get the episode in every language you want and then just merge them yourself with ffmpeg.
