### ISSUE TITLE
Sing in with my chrunchyroll account

### ISSUE THREAD

**Issue by Killuad** [hama3254/Crunchyroll-Downloader-v3.0#57]
I've been trying to download premium content in chrunchyroll but when i try to do it show me this.
![Captura de pantalla (26)](https://user-images.githubusercontent.com/71679711/93837210-e0f2a800-fc4a-11ea-90d0-dd5572b58d88.png)

I remember in before versions we had the option to log in with our chrunchyroll account and now i cant find it. ¿Is there any option to enable this again?

**Comment by hama3254** [comment]
You can Open the build in Browser with the second Icon fom the top left.
By Default it should Open crunchyroll where you can Login normaly.

**Comment by Killuad** [comment]
Thank you for your assitance. I have a quiestion that may not be related with this program but, you have any way to dowload anime from  funimation too?

**Comment by hama3254** [comment]
> Thank you for your assitance. I have a quiestion that may not be related with this program but, is there any way to download anime from funimation?

i added funimation after v3.3.1 to the downloader, i just updated the firefox add-on and the downloader to work better with funimation and crunchyroll.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.4.5

just one thing is to consider, you need to login in the downloader because i don't understand (yet) how funimation serves englisch dub or japanese dub. 
this need to be set in the account and you need to be logged in to use the account setting.

**Comment by Killuad** [comment]
Thank you again. You were very helpfull
