### ISSUE TITLE
Japanese and English treated as separate seasons

### ISSUE THREAD

**Issue by lucky1804** [hama3254/Crunchyroll-Downloader-v3.0#574]
Currently downloading Twin Star Exorcists and on CR there are two version, one is English dub and one is original Japanese with English subs, this series has only one season but when downloading English version it shows up as Season 1 in downloader and file name but when downloading Japanese version it is showing up as season 2.

Is there anything that can be done as a workaround since it seems to be Crunchyroll issue as they are labeling Japanese version as season 2

CR website:
![image](https://user-images.githubusercontent.com/202993/198742685-4fe63f2d-8490-45d0-a118-767637ea549b.png)

Downloader:
![image](https://user-images.githubusercontent.com/202993/198742893-99a8adb6-6159-48ec-ba31-8249ed6ea70e.png)

Filenames:
![image](https://user-images.githubusercontent.com/202993/198743474-27b3aaa5-5136-4c9d-97c7-a58bc4666f35.png)

**Comment by MattRBX** [comment]
This is a Crunchyroll problem and I don't know why they haven't done anything to change it.

I guess you might be able to do something with the coding to detect whether its a dub or a second season. But because of the way Crunchyroll is made this is how it is by default.

**Comment by hama3254** [comment]
This is rather difficult to detect and since CR is improving i don't see any reason to even attempt any workaround.

![grafik](https://user-images.githubusercontent.com/52826614/198829356-5b7b005e-483e-4b55-b413-4ed7798d164c.png)
![grafik](https://user-images.githubusercontent.com/52826614/198829396-3163af72-9e09-4ff4-9848-97bea7961abe.png)
