### ISSUE TITLE
youtube video for hybrid mode is gone

### ISSUE THREAD

**Issue by Djidjo2** [hama3254/Crunchyroll-Downloader-v3.0#583]
not really a bug but i wonder what "hybrid mode" means, and since in the doc the answer is a youtube video which is gone... can you explain it here or post video somewhere else ? I didn't see any noticeable difference when trying, at least no difference in freezing after 1st dl. Thanks !

**Comment by hama3254** [comment]
The video was removed from YT and the readme is not only unfished but also very outdated.

The `hybrid mode` uses the design of the video stream which is split into small segments of the full video with a lengh of a view seconds. 
The video processing software that i use (`ffmpeg.exe`) to process the stream only gets one of the segments and writes it into the output file while the hybrid mode downloads all files directly before i start the processing with `ffmpeg` so this access will be faster since even slow local storage is still faster than accessing something on the internet.
The hybrid mode is also designt to work in parallel so it can download more segemts at the same time, this depends on your hardware to not overload old systems the default is half the `logical processors`.

![grafik](https://user-images.githubusercontent.com/52826614/200166344-607abfcd-3bba-4d63-8288-aa8a2570ea23.png)

**Comment by Djidjo2** [comment]
thanks for the info ! i suppose then that "hybrid keep cache" means those segments are not deleted after processed.
