### ISSUE TITLE
The size of the episode is very large

### ISSUE THREAD

**Issue by RamiBadyan** [hama3254/Crunchyroll-Downloader-v3.0#588]
The size of the episode is very large, more than 1 GB!
How do I make the episode less than 1 GB ?

**Comment by hama3254** [comment]
The simple solution would be to lower the resolution.

The more advanced solution would be [Video compression](https://www.youtube.com/watch?v=r6Rp-uo6HmI).

Your name does not sound like you can understand the German explanation from here https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/528#discussioncomment-3620513 so here is the Englisch version:

Video compression works with different methods like [h265 also know as HEVC ](https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding) and the older [h264/'Advanced Video Coding'](https://en.wikipedia.org/wiki/Advanced_Video_Coding).
`h265` is much better than h264 but has not yet replaced it, this can cause playback issues.
I would recomend testing one episode to see if h265 works for you and if not you can use h264.

- **purple** this is the default and gives you the best quality available but the files are as you mentioned somewhat big.

- **green** This uses [special hardware inside nvidia GPU's](https://en.wikipedia.org/wiki/Nvidia_NVENC) to process the video, this makes it much faster than in software. 

- **black** This are software encoders and use the CPU of your Computer for the processing, this takes more time than hardware enoders and you should not use the computer at the same time since the use 100% of the avalible power 

- **red**  The same as green just for AMD GPU's.

- **blue** Intel CPU's have an build in GPU that can be used if avalible with this option, this also seem to work with Intel Arc cards.

you can adjust the file size with the `-b:v` setting,  `8000k` would be the default that CR gives you so `4000k` would mean the size of the file is now half as big (for 1080p).
This is not magic, the lower you go the worse the video will look. You can try for yourself what you want, it is always a trade of between storage and quality.

for the `preset` i did not see any differneces so i just use `fast` .

![grafik](https://user-images.githubusercontent.com/52826614/189542201-152378d3-512a-410f-a78a-6ff636364823.png)

**Comment by flagg19** [comment]
> The size of the episode is very large, more than 1 GB! How do I make the episode less than 1 GB ?

I like to store what I watch, to be able to re-watch it in the future, so I've done a lot of tests to find the settings for the best quality at the smallest possible file size. I ended up with two profiles, one for 1080p anime that I use for "high quality" anime 
 (that have good graphics/animations) and one for 720p anime that I use for less graphically intense shows.

Final sizes are:
- 1080p:  between 250mb and 450mb
- 720p: between 150mb and 350mb

For both, quality is almost indistinguishable from the original.

You could compress (re-encode) the files directly with CRD as hama3254 has explained you, but I prefer to let CRD do what it does best, that is, download the untouched files, and then compress them with a dedicated free software (that under the hood uses the same libraries, but is easier to use and gives more flexibility IMO) that is [handbrake](https://handbrake.fr/). 

If you are interested, here are my handbrake presets: [presets.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/9997081/presets.zip)

They are pretty slow, for better quality I use h265 cpu encoding, on a 3700x it takes 10 minutes for a 720p episode, 15 for a 1080p episode.

**Comment by RamiBadyan** [comment]
> The simple solution would be to lower the resolution.
> 
> The more advanced solution would be [Video compression](https://www.youtube.com/watch?v=r6Rp-uo6HmI).
> 
> Your name does not sound like you can understand the German explanation from here [#528 (comment)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/528#discussioncomment-3620513) so here is the Englisch version:
> 
> Video compression works with different methods like [h265 also know as HEVC ](https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding) and the older [h264/'Advanced Video Coding'](https://en.wikipedia.org/wiki/Advanced_Video_Coding). `h265` is much better than h264 but has not yet replaced it, this can cause playback issues. I would recomend testing one episode to see if h265 works for you and if not you can use h264.
> 
> * **purple** this is the default and gives you the best quality available but the files are as you mentioned somewhat big.
> * **green** This uses [special hardware inside nvidia GPU's](https://en.wikipedia.org/wiki/Nvidia_NVENC) to process the video, this makes it much faster than in software.
> * **black** This are software encoders and use the CPU of your Computer for the processing, this takes more time than hardware enoders and you should not use the computer at the same time since the use 100% of the avalible power
> * **red**  The same as green just for AMD GPU's.
> * **blue** Intel CPU's have an build in GPU that can be used if avalible with this option, this also seem to work with Intel Arc cards.
> 
> you can adjust the file size with the `-b:v` setting, `8000k` would be the default that CR gives you so `4000k` would mean the size of the file is now half as big (for 1080p). This is not magic, the lower you go the worse the video will look. You can try for yourself what you want, it is always a trade of between storage and quality.
> 
> for the `preset` i did not see any differneces so i just use `fast` .
> 
> ![grafik](https://user-images.githubusercontent.com/52826614/189542201-152378d3-512a-410f-a78a-6ff636364823.png)

Thank you very much, I understand now.
