### ISSUE TITLE
Download crash

### ISSUE THREAD

**Issue by Gumball4041** [hama3254/Crunchyroll-Downloader-v3.0#59]
Hi, I'm having some problems downloading everything. It always worked perfectly but now everything I try to download crashes.
I attached a screen of what happen and I uploaded on Drive all the logs. Hope they'll be helpful. https://drive.google.com/drive/folders/1gCIY4oU9sJiuGe-CfBa-a4o9E43ZO7v0?usp=sharing
(I don't know if this could be related but I can't change the simultaneous downloads number in the settings too... it's stuck on 2)
![Immagine 2020-09-28 211425](https://user-images.githubusercontent.com/41842794/94476094-49540300-01d0-11eb-9dd9-f782cf73ee09.jpg)

**Comment by hama3254** [comment]
it seem like you have a problem with the settings: 
`28/09/2020 21:14:06  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_nvenc))`
`...`
`28/09/2020 21:14:07[h264_nvenc @ 07363140] Cannot load nvcuda.dll`
`28/09/2020 21:14:07Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height`
for the settings `h264_nvenc` and `hevc_nvenc` is a Nvidia graphic card Series 700 or later required.
![grafik](https://user-images.githubusercontent.com/52826614/94478419-8a014b80-01d3-11eb-810f-9bc9954495fb.png)

> I don't know if this could be related but I can't change the simultaneous downloads number in the settings too... it's stuck on 2

it is locked to 2 because of the Nvidia Nvenc encoder does not allow more on a driver level. 

[From Wikipedia :](https://en.wikipedia.org/wiki/Nvidia_NVENC)

> Consumer targeted GeForce graphics cards officially support no more than 2 simultaneously encoding video streams, regardless of the count of the cards installed, but this restriction can be circumvented on Linux and Windows systems by applying an unofficial patch to the drivers.[6] Professional cards support between 2 and 21 simultaneous streams per card, depending on card model and compression quality.

the simplest solution is to use the `-c copy` setting. this cost more space than re-encoding to h264 with 7000k or less but it does not require much computing power like libx264 or libx265 (this are also locked at a single download simultaneously because it does not speed anything up anyway and the most consumer CPU's need a lot of time to re-encode videos)

**Comment by Gumball4041** [comment]
Thank you so much. I changed that setting and i forgot to restore it.. I'm stupid
