### ISSUE TITLE
The download process seems to have crashed in some videos

### ISSUE THREAD

**Issue by pruebark9** [hama3254/Crunchyroll-Downloader-v3.0#598]
Version : 3.9 U8 and 3.9 portable 5

Today I receive this error in 4 videos. Specifically they are

https://www.crunchyroll.com/es/watch/GG1U28Q4D/echo
https://www.crunchyroll.com/es/watch/GEVUZ92XK/crime-and-punishment
https://www.crunchyroll.com/es/watch/G7PU4QZMX/first-guardian
https://www.crunchyroll.com/es/watch/G9DUE8Q5Q/on-the-other-side-of-love-and-hate

It only happens to me with those 4 videos. The rest, it works without any problem. I thought it was my version so I tried the latest one and nothing, I always get the same error.

<details>
  <summary>Insert the logtext before the second details</summary>

[Bungo Stray Dogs 3 37.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10095196/Bungo.Stray.Dogs.3.37.log)

    
</details>

**Comment by drox22** [comment]
Ich hab ein ähnliches Problem bei den Episoden die gestern und heute rausgekommen sind. 
Die gehen garnicht, da steht nur: "Press the play button again to retry"
https://www.crunchyroll.com/de/watch/G31UX1ZQE/anima-and-animus
https://www.crunchyroll.com/de/watch/GWDU8X12X/its-a-resort-everybody
https://www.crunchyroll.com/de/watch/GG1U28080/

![ptpbatr](https://user-images.githubusercontent.com/119075644/204075260-0dd65e7a-231c-47b1-bf48-358b104b09c3.JPG)

Und dann habe ich noch was seltsames bemerkt, die Folgen die gestern rausgekommen sind und sich runterlanden lassen. Die haben keine Font. Also nicht die normale Crunchy Schriftfarbe mit der schwarzen umrandung, sonder nur weiß.

https://www.crunchyroll.com/de/watch/GMKUXKDWN/ripple
https://www.crunchyroll.com/de/watch/G50UZQ9P5/

ich benutze hybrid mode und hardsub
![font](https://user-images.githubusercontent.com/119075644/204075258-7d48191d-4b96-4187-bc89-91fbfaf02ac4.JPG)

**Comment by hama3254** [comment]
if this are all new episodes than it's probalby the same issue as https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/550#discussioncomment-4241819.
This would mean the [new verison is already avalible here](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Portable)

**Comment by hama3254** [comment]
> but do you now why the font changed?

if you use hardsubs then this i a changed from crunchyroll since hardsubs are part of the video itself

**Comment by pruebark9** [comment]
Yes, it works without any problem and it also starts the program and downloads much faster. Thank you very much.

**Comment by Isaias-Barbosa** [comment]
Ok, After installing the new portable version and installing the webView2 RunTime, this error occurs to me.
![image](https://user-images.githubusercontent.com/49703882/204109638-9dd92d6d-a1b8-46fc-855c-c8ec9fe9a21d.png)

**Comment by hama3254** [comment]
@Isaias-Barbosa this means the webserver refuses to give you the requested data.
This can only be an invalid url since there is nothing else required please look at your log and see if an url with `crunchyroll/objects` is in there.
the log shows with a click on that bar.
![grafik](https://user-images.githubusercontent.com/52826614/202715015-2cf56682-79fc-4ba2-88ae-c4fb3dedc4ef.png)

**Comment by Isaias-Barbosa** [comment]
> @Isaias-Barbosa this means the webserver refuses to give you the requested data. This can only be an invalid url since there is nothing else required please look at your log and see if an url with `crunchyroll/objects` is in there. the log shows with a click on that bar. ![grafik](https://user-images.githubusercontent.com/52826614/202715015-2cf56682-79fc-4ba2-88ae-c4fb3dedc4ef.png)

Indeed, there is a URL error, but what could it be? I'm using the correct CR link: https://www.crunchyroll.com/pt-br/watch/G14U4N5PQ/detour
![image](https://user-images.githubusercontent.com/49703882/204365656-6c5aa392-1c66-452d-9abf-70e4f1a6b11f.png)
![image](https://user-images.githubusercontent.com/49703882/204365471-0f482904-a7a0-4638-8881-0c0c45d8d8a9.png)

**Comment by hama3254** [comment]
What i can see on your log is that the location indicates a Germany based request.
I would assume with the `pt-br` that this is unlikey your location (?) but it seems to require a german IP adress otherwise the server refuses the connection.
(or at least `DE` does not work with a US IP and every new request changes that to `US`)
![grafik](https://user-images.githubusercontent.com/52826614/204379064-cd18ae3e-6da2-43f1-93ec-df5f47d975e6.png)

just for reference, i get the data is from CR.
![grafik](https://user-images.githubusercontent.com/52826614/204381763-1530b143-35c8-4ce6-948e-4e97f3bdf78a.png)

**Comment by hama3254** [comment]
Since the original problem is solved i will close this and for @Isaias-Barbosa your error seems to get worse, more about that inside #608
