### ISSUE TITLE
Feedback for WebView V2_Test

### ISSUE THREAD

**Issue by ms-ku** [hama3254/Crunchyroll-Downloader-v3.0#601]
Hello

I don't know if i can open a new Topic, but i think this is good for a better overview (if not please merge it to right place)

At the moment i can say to the WebView V2_Test
- No freezing
- No "Nothing found"
- No skipping files (by full load cpu and intenet connection)

Currently it looks very good! 

Thank you very much for your work hama !!!

Greetings
msku

**Comment by Serpentstar** [comment]
When I open the browser, I get nothing at all.
![image](https://user-images.githubusercontent.com/751507/204118005-c13105a0-a16f-40c9-b03a-0c86130e3174.png)
I even tossed it on a VM with lower security, and still have the same results.

**Comment by ms-ku** [comment]
Hello
I know, stupid question but is WebView2 Runtime installed?
Greetings
msku

**Comment by hama3254** [comment]
@Serpentstar 

>You may also require the [WebView2 Runtime from Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) and to login into Crunchyroll with the build-in webbrowser.

**Comment by Serpentstar** [comment]
Not a stupid question at all and that explains it.  It also means I won't be able to use the program any more since you have specifically moved to the Edge Browser which is not uninstalled and I also have Internet Access denied to it for any possible services.

![image](https://user-images.githubusercontent.com/751507/204140166-dd8968c1-ca31-4277-b146-4736d0c37168.png)

Was there a reason for the move to do Microsoft Browser dependency on this version?  I didn't have issues launching the previous versions.

**Comment by hama3254** [comment]
> I won't be able to use the program any more since you have specifically moved to the Edge Browser which is not uninstalled and I also have Internet Access denied to it for any possible services.

This means you disabled the Edge Browser for yourself on puropse ? 

>Was there a reason for the move to do Microsoft Browser dependency on this version? I didn't have issues launching the previous versions.

You might not had any issues but there where a lot of reports for freezing which seems to come from the CefSharp Browser i used.
The WebView2 is faster and simpler to work with due to other multi threading behavior. It also has security benefits since the runtime can be updated without the downloader.

**Comment by Serpentstar** [comment]
re: Edge.  I didn't disable it, I uninstalled it.  I don't like programs that reach out to the internet without me telling them to.  The svchost.exe process does enough of that as it is.

I was able to permit just MSEDGEWEBVIEW2.EXE access and your program seems to work with that.  Blocking the remainder of the components don't seem to prevent it.  

Thank you again for such a wonderful program.
