### ISSUE TITLE
Error when pasting the url

### ISSUE THREAD

**Issue by Gabrielfsn** [hama3254/Crunchyroll-Downloader-v3.0#605]
![image](https://user-images.githubusercontent.com/79546729/204393965-8a7e92d3-1f3e-4654-8b29-581d49a2c3cf.png)

I have no idea what is causing this, a few days ago the indev version worked normally.

**Comment by hama3254** [comment]
The library for getting data from CR could not verify the server with it's certificate. This error would mean that CR just made the certificate themselfe instead of an [Certificate authority](https://en.m.wikipedia.org/wiki/Certificate_authority) you can use the `insecure` option inside the settings to simply ignore the error.
