### ISSUE TITLE
EsLa Hardsubs - Crunchyroll

### ISSUE THREAD

**Issue by xslaayer29** [hama3254/Crunchyroll-Downloader-v3.0#644]
**Describe the bug**
In each download it is detected as dubbing in English (even though the dubbing is in Japanese), and the Hardsubs in Spanish (LA) do not work, but the others do work. This for crunchyroll downloads. Until a few days ago it worked normally.

![Captura de pantalla (21)](https://user-images.githubusercontent.com/89604781/209838549-30cb40fe-f226-45ad-b3da-fa1d8bdf896a.png)
![Captura de pantalla (22)](https://user-images.githubusercontent.com/89604781/209838575-42122b85-eea9-4b1b-b0de-a6b3b14248b9.png)
![Captura de pantalla (23)](https://user-images.githubusercontent.com/89604781/209838588-0bc50c7f-ff43-4799-a636-92a9280abe50.png)

**Comment by hama3254** [comment]
> In each download it is detected as dubbing in English (even though the dubbing is in Japanese),

This is due to mislabeled data from CR 

>i did not try much but it seems like the new api has wrong data for the language 
i selected the `OmU` version (german for [original version with subtitles](https://de.wikipedia.org/wiki/OmU)) so it should be `ja-JP`
![grafik](https://user-images.githubusercontent.com/52826614/209692898-9a9f7f88-a90c-48c8-9db8-5c59e456c7d4.png)
>
>_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/632#issuecomment-1366025808_


>and the Hardsubs in Spanish (LA) do not work, but the others do work. This for crunchyroll downloads. Until a few days ago it worked normally.

i am currently unable to reproduce the issue, please make sure you use the latest version,

![grafik](https://user-images.githubusercontent.com/52826614/209875843-2b289bc8-5936-44ec-aa2b-40794fae3140.png)

**Comment by hama3254** [comment]
please try [v3.11.3 ](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.11) this should fix the language issue and the dub language should be closer to correct.

**Comment by xslaayer29** [comment]
Thanks !!!!!  I'll try

**Comment by xslaayer29** [comment]
It's working, thank you very much!!!!!!!!!
