### ISSUE TITLE
Bug with speed download

### ISSUE THREAD

**Issue by AnonymousRabbit** [hama3254/Crunchyroll-Downloader-v3.0#652]
Hello, already thank you for this amazing job ❤️. 

The bug: I have a very big slowdown in download speed with the latest version (v3.12), a problem I don't have with v3.11.3.

**Comment by hama3254** [comment]
Please check your settings or important the `User.config.dat` from your last version.

**Comment by AnonymousRabbit** [comment]
I just replaced this file with the one from the old version, it works a little better, but it's still pretty slow.

**Comment by AnonymousRabbit** [comment]
I see. I had checked before putting up what I thought was a problem that the parameters were the same (and they are). 

![image](https://user-images.githubusercontent.com/120563372/210602464-6a801580-bb76-4d4c-a5ca-ad315d4c8c56.png)

I should also point out that there are only a few minutes between my tests of the new version and the old one. Also, I directly retested the old version which still works the same way. This is where my questioning comes from (sorry, I was not clear enough) .

**Comment by hama3254** [comment]
One thing that has changed in the background is the ffmpeg version, i use a newer version and with me using the `Hybrid Mode` all the time i don't know the impact for downloading directly with ffmpeg.
If you set the Download Mode to `Hybrid Mode` it should get much faster than ffmpeg is.
This works by caching the data so ffmpeg has much faster access (bandwith and access time) to the file while the `Hybrid Mode` itself is faster in downloading since it is working in parallel. 
![grafik](https://user-images.githubusercontent.com/52826614/210604668-3d25c156-0779-4e45-8482-d60145af433c.png)

**Comment by AnonymousRabbit** [comment]
oh ok, i see. Thanks.

**Comment by hama3254** [comment]
See #653
