### ISSUE TITLE
nvenc_hevc crash problem

### ISSUE THREAD

**Issue by ManuelDiazIsaza** [hama3254/Crunchyroll-Downloader-v3.0#664]
**Describe the bug**
When i try download with hevc_nvenc i always have crash error

![image](https://user-images.githubusercontent.com/37357573/212430925-e54a18eb-d40e-4549-8fe2-89f000c87658.png)

In version 3.11.3 work fine but i have a lot of problem with the select resolution problem

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings MP4 hevc_nvenc
 - Version 3.13.1

**Screenshots**
![image](https://user-images.githubusercontent.com/37357573/212431215-a5c9ae73-22d4-41c7-9886-d5ea54c158a5.png)

**Additional context**

**Comment by rcyclope** [comment]
i have the same pb!

```
13/01/2023 22:56:43   Duration: N/A, bitrate: N/A
13/01/2023 22:56:43   Stream #1:0: Subtitle: ass
13/01/2023 22:56:43 Stream mapping:
13/01/2023 22:56:43   Stream #0:0 -> #0:0 (h264 (native) -> hevc (hevc_nvenc))
13/01/2023 22:56:43   Stream #0:1 -> #0:1 (copy)
13/01/2023 22:56:43   Stream #1:0 -> #0:2 (copy)
13/01/2023 22:56:43 Press [q] to stop, [?] for help
13/01/2023 22:56:43 [hevc_nvenc @ 000001fdde180900] B frames as references are not supported
13/01/2023 22:56:43 [hevc_nvenc @ 000001fdde180900] No capable devices found
13/01/2023 22:56:43 Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
13/01/2023 22:56:43 Conversion failed!
```

[Revenger s01 E01 Once Upon a Time in Nagasaki.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10416728/Revenger.s01.E01.Once.Upon.a.Time.in.Nagasaki.log)

**Comment by ManuelDiazIsaza** [comment]
With av1 codec i have the same error

**Comment by hama3254** [comment]
for @ManuelDiazIsaza  please check the log, i can not guess your issue since i have no data of your hardware.

For @rcyclope would the error `[hevc_nvenc @ 000001fdde180900] B frames as references are not supported`  mean you don't have any RTX card but maybe something older.
This lead to an issue since i am able to run more since according to the [Wikipedia list of GPUs and there hardware encoder ](https://en.wikipedia.org/wiki/Nvidia_NVENC#Versions) my `GA102` can handle `B Frames` while the `TU117` aka GTX 1650 an lower can not.
The exact hardware data would help with finding a solution, you can find the codename of your GPU with [`GPU-Z`](https://www.techpowerup.com/gpuz/) 
![grafik](https://user-images.githubusercontent.com/52826614/212465976-0c823cd0-bc14-4213-8440-b8279e77d596.png)

if for both of you `In version 3.11.3 work fine` is true than it could be ffmpeg related and you could try using the `ffmpeg.exe` from the v3.11 inside the v3.13.1. This will make `libsvtav1`, `av1_nvenc` and `av1_qsv` to crash every download.

**Comment by ManuelDiazIsaza** [comment]
@hama3254 i put the ffmpeeg of 3.11.3 in 3.13.1 and work fine now, thanks

**Comment by hama3254** [comment]
the latest v3.14 is back to the old ffmpeg version, the new av1 options will also display a warning that they won't work with the included ffmpeg version. This is the best i can do for now.
