### ISSUE TITLE
tons of erros on crunchyroll using hama with hybrid download

### ISSUE THREAD

**Issue by dkb007** [hama3254/Crunchyroll-Downloader-v3.0#68]
![image](https://user-images.githubusercontent.com/23116307/95673079-38899100-0bc3-11eb-8eb4-885258326fcb.png)
Getting tons of error when an episode is downloader from CR using with hybrid on, they show when changing container mp4 to mkv.

Files downloaded from Funimation with hybrid on gives no error, it only happens with files from CR.

`@echo off & setlocal enabledelayedexpansion
for %%v in ("*.mp4") do (
  set FileName=%%v

C:\ffmpeg\bin\ffmpeg.exe -i "!FileName!" -c copy -map 0 "!FileName:~0,-4!.mkv"
)
pause`

This script I am using to change the mp4 container to mkv.

Here are the logs : one is for video checking log (which shows the errors) and the other one is the CR downloader log after downloading the file
[One_Piece_Season_13_Episode_945.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5360735/One_Piece_Season_13_Episode_945.log)
[One_Piece_Season_13_Episode_945.mkv.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5360736/One_Piece_Season_13_Episode_945.mkv.log)

**Comment by hama3254** [comment]
I see three issues here:

- i can not reproduce your issue : https://www.youtube.com/watch?v=yFBX3er3CZ4

- This has anyway nothing to do with the download

- and since you most likely don't responde anyway like at the issues https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/62 and https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/67 i will close all of them

**Comment by dkb007** [comment]
Sorry for those not replying, I will try to create a list of steps to reproduce I think
