### ISSUE TITLE
Custom FFMPEG

### ISSUE THREAD

**Issue by holobestwaifu** [hama3254/Crunchyroll-Downloader-v3.0#682]
I really like the way FFMPEG is integrated into the application but would it be possible to have custom FFMPEG commands?
I tried just editing the `User.config.dat` but I didn't get any results from that.
It would be great to have a tick box in the UI or just a config file to do that.

**Comment by hama3254** [comment]
the only two options that change the ffmpeg command are the merged sub option and the encoder, more options are not planned since it gets complicated really fast.

<details>
  <summary>example ffmpeg command</summary>
  
```
-user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0" -headers "ACCEPT-ENCODING: *" -i "[Video.m3u8]" -i "[Subtitle.ass]" -map 0:v -map 0:a -map 1 -c:v av1_qsv -preset fast -b:v 1500k -c:a copy -bsf:a aac_adtstoasc -c:s copy -metadata:s:s:0 language=ger -metadata:s:s:0 title="Deutsch" -metadata:s:s:0 handler_name="Deutsch" -disposition:s:0 default -metadata:s:a:0 language=eng "Out.mkv"
```

  
</details>

**Comment by holobestwaifu** [comment]
I know what you mean but for example when I want to encode with a library that is not one of those in the default list or when I want to pass more arguments than the defaults, I have to re-encode the file afterwards. That's not impossible but it is a bit inconvenient.

**Comment by hama3254** [comment]
I hope this enough options, more access would mean major changes to the code.
I am not even sure how the settings react to changes there so i would advice to make a backup of the `User.config.dat` since that command is directly saved after you hit ok.

![grafik](https://user-images.githubusercontent.com/52826614/214683796-9f3d0ccb-1ee1-4073-a2cd-5b8947d0122c.png)

**Comment by holobestwaifu** [comment]
That's actually perfect!
Thank you very much!

Changing the settings in the file just broke the parser ¯\_(ツ)_/¯

**Comment by x3inspire** [comment]
> That's actually perfect! Thank you very much!
> 
> Changing the settings in the file just broke the parser ¯_(ツ)_/¯

Can you share the ffmpeg command u used?

**Comment by holobestwaifu** [comment]
@x3inspire 
I basically stole it from [here](https://kokomins.wordpress.com/2019/10/10/anime-encoding-guide-for-x265-and-why-to-never-use-flac/) with a few small modifications
`-c:v libx265 -preset slow -crf 24 -x265-params "bframes=8:psy-rd=1:aq-mode=3:aq-strength=0.8:deblock=1,1:log-level=1" -c:a copy`

**Comment by x3inspire** [comment]
> @x3inspire I basically stole it from [here](https://kokomins.wordpress.com/2019/10/10/anime-encoding-guide-for-x265-and-why-to-never-use-flac/) with a few small modifications `-c:v libx265 -preset slow -crf 24 -x265-params "bframes=8:psy-rd=1:aq-mode=3:aq-strength=0.8:deblock=1,1:log-level=1" -c:a copy`

Can i use those command for other video, like movie and series other than anime? Does it good?

**Comment by hama3254** [comment]
The default input box did not work as expected so i made one myself.

the settings may bug out but it was not to bad with the ffmpeg command you provided
![grafik](https://user-images.githubusercontent.com/52826614/215272425-02206a7a-b78c-40c5-aafd-2739cd7d0f1b.png)

This issue that the settings may reset your command is fixed with ignoring any change as long the override is set as current command
![grafik](https://user-images.githubusercontent.com/52826614/215272917-3a00d5e1-1a88-459d-9144-93db474eb88a.png)

this can only be canceld out with using `null` as command and restarting the downloader to load the old command.
![grafik](https://user-images.githubusercontent.com/52826614/215272827-ed399a3b-32b0-483e-a948-567e86a2bf69.png)

**Comment by holobestwaifu** [comment]
It works perfectly, vielen Dank!

**Comment by janilssonn** [comment]
![image](https://user-images.githubusercontent.com/16007846/216843344-7e79b3f3-34c8-4ede-bbcf-77bf6bad995d.png)
I have this error
