### ISSUE TITLE
how to have the videos, with several audio languages ?

### ISSUE THREAD

**Issue by mortifia** [hama3254/Crunchyroll-Downloader-v3.0#695]
example 
english and jap

if that's not possible, don't worry
(at least having the dl of the 2 will be nice (it avoids changing the configuration each time))

![image](https://user-images.githubusercontent.com/22671054/219584154-84a29342-a6c3-404c-b2a3-f16a12b49d58.png)

- https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/693
- https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/673
- https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/677

**Comment by hama3254** [comment]
I already mentioned in [this German comment](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/677#issuecomment-1416859411) that the dub option itself is only to set some request variables.
This means you get the audio language of the episode without the download changing it.
This is also the reason the downloader adds all versions to the season selection instead of hiding them.
I still have no answer to some design choices so i keep it as it was, you decide the versions with the url.

The use of that option may be subject to change but what i am very sure is that there will never be multiple dubs per video as explained in #693.

**Comment by mortifia** [comment]
ok thanks for the response !
