### ISSUE TITLE
Foreign language dubs are not only displayed in the series selection

### ISSUE THREAD

**Issue by ms-ku** [hama3254/Crunchyroll-Downloader-v3.0#721]
Hello
Is there a setting that only the episodes of the existing foreign language dubs (e.g. German) are displayed?
I mean that this was so in the past. CRD fills them up with existing origin episodes.
Thanks and greetings
msku

![image](https://user-images.githubusercontent.com/67540232/227784102-aec6a523-27af-49e4-9bdd-4c130081a2ad.png)

**Comment by hama3254** [comment]
>I mean that this was so in the past

Before they merged the other dubs they had no other way as just to display the available episodes and as far as I remember they kept it that way and just made the other seasons invisible.

I don't know how the browser displays it but if they fill the season up with the wrong dub that would be stupid.
With a quick look they at least do that on the API.

I personally would not even add an option but just discard all episodes with another dub tag than the season because you already make a decision with the selection on top.

**Comment by ms-ku** [comment]
Hello Hama
thank you very much. It works! :-)))
You wrote "Before they merged the other dubs" - can one understand it in that way that it would be possible to download several dubs (eg Japanese and German) in one download?
Thanky you and greetings
msku

**Comment by hama3254** [comment]
>that it would be possible to download several dubs (eg Japanese and German) in one download?

Yes, but it's not implemented.
The closest you can get to that would be with #701
