### ISSUE TITLE
Download stops for no reason

### ISSUE THREAD

**Issue by LiiQuii** [hama3254/Crunchyroll-Downloader-v3.0#728]
With the current version, I keep having the problem that downloads just stop making progress at some point. They aren't recognized as crashed, but simply don't do anything anymore.
I've only seen this behavior when the internet connection is down, but now it seems to happen randomly on some downloads for no apparent reason. Even with simultaneous downloads, it only affects a few.

If I then manually cancel the download and start it again, everything works again and I can hope again that it will come through.

 - Version v3.15.1

Settings:
- Simultaneous Downloads: 3
 - Error Handling: 0

[Log.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/11175038/Log.txt)

**Comment by hama3254** [comment]
The log does not contain anything unusual, if there is an issue it might be within the [`ffmpeg`](https://ffmpeg.org/about.html) library.
Something you can try would be to use the `Hybrid Mode`, with this the downloader will make a 1:1 copy of the stream before forwarding the data to `ffmpeg` this has speed improvents (due to multithreading) and should also be more reliable.
![grafik](https://user-images.githubusercontent.com/52826614/230577741-194a3347-1022-4c42-a9cc-51e2b5fd24b4.png)

**Comment by LiiQuii** [comment]
Thanks for the tip, I'll try it and give you feedback as soon as possible

**Comment by LiiQuii** [comment]
After further experimentation, your assumption that it is due to `ffmpeg` seems to be correct. Sometimes when a download is aborted, the file cannot be deleted because it is still open in `ffmpeg`. so it is very likely that the problem lies there.
With your tip it runs more stable now, thank you very much
