### ISSUE TITLE
Bug and requests

### ISSUE THREAD

**Issue by San3-Cod3** [hama3254/Crunchyroll-Downloader-v3.0#741]
There's a bug I noticed - where the file will say download complete when it hasn't yet reached 100% and hasn't actually completed yet, at times it could stop early or near the end; other times the file will appear entirely complete and finished, but the file will have a tiny part of corruption; or missing frame piece, a few seconds chunk missing or skip here or there etc...  This happens to some files when doing a batch, with the max 12 being fetched.

This was on Windows 10.

I tried to use the software on my Win 7 system, I know it isn't supported and I got this error: 
http://puu.sh/JGJ32/1b9443a438.png

Any chance a future version could support 7? This is a feature request.  I believe it'd be a more stable application if it could run on 7; I truly believe this.

Second feature request:
Can we have more customisation options over the final file's entire name output, e.g.

{seriesTitle}/{seasonTitle}/ FOLDERS CREATED WITHIN CHOSEN DIRECTORY - and here we can modify entire portions of the file name e.g. [Group Name I.E CR Funi] {seasonTitle} - Eps.{episodeNumber} ~ {episodeTitle} [{resolution}] [{CRCNUMBER}]
Translates to e.g.: [Funi] 86 EIGHTY SIX (English Dub) - Eps.#01 ~ Undertaker [1080p] [ABCDE1234]

So we can have Episode or Eps.; Season or S - short or long form, resolution inclusion, final CRC inclusion if possible, Group Name, and just a general way to order and organise the entire name more, before saving, I love the checkbox idea, but maybe an advanced box to modify those values ourselves so it can be like above example, and a way to include our own extras into the name, all automated that we can save as permanent settings as it'll save time when archiving.

Thanks for your consideration and understanding, and thank you for your contribution!

**Comment by hama3254** [comment]
> where the file will say download complete when it hasn't yet reached 100% and hasn't actually completed yet, at times it could stop early or near the end;

The UI only processes the data recived from the [`ffmpeg`](https://ffmpeg.org/) sub process, if does not exit correctly you might see this behavir. The reason would need looked up within the [FFMPEG-Logfile](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile).

> other times the file will appear entirely complete and finished, but the file will have a tiny part of corruption; or missing frame piece, a few seconds chunk missing or skip here or there etc

This can happen due to the nature of the stream which is split into fragments with 2-10 seconds each, the defaul ffmpeg download only skips fragements if they can not be downloaded.
The hybrid mode try's to redownload them once and has a longer timeout duration.
 
> This happens to some files when doing a batch, with the max 12 being fetched.

To speed up the download, the `Hybrid Mode` would be the better choice than just more downloads, i dont recommend more than 2 downloads at the same time.


> I tried to use the software on my Win 7 system, I know it isn't supported and I got this error: http://puu.sh/JGJ32/1b9443a438.png
> 
> Any chance a future version could support 7? This is a feature request. I believe it'd be a more stable application if it could run on 7; I truly believe this.

No.

> Can we have more customisation options over the final file's entire name output, e.g.

See #645

>Translates to e.g.: [Funi] 86 EIGHTY SIX (English Dub) - Eps.https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/1 ~ Undertaker [1080p] [ABCDE1234]

This title looks surprisingly similar to the titles of piracy websites.
