### ISSUE TITLE
Getting m3u8 error

### ISSUE THREAD

**Issue by pratyushpati11** [hama3254/Crunchyroll-Downloader-v3.0#748]
**Describe the bug**

**Where does the issue happen?**
 - Platform: [Crunchyroll]
 - Settings [Softsubs, ffmpeg default]
 - Version [v3.15.3]

**Screenshots**
[](https://imgur.com/a/SDtrrZP)
![Screenshot (1249)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/92674784/b19be045-013c-47e0-9ec4-e54f83162f4f)
![Screenshot (1249)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/92674784/4d531511-d0e0-493a-9b30-c12bb46e22fc)

**Additional context**
When I choose Auto option in video version the download keep crashing

**Comment by hama3254** [comment]
seems the same issue like [#743](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/743#issuecomment-1555861327) and there is no solution even with the client reciving a [`400`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) which would be a client error but cloudflare tells me its a [`502`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502) which is a server issue.

**Comment by pruebark9** [comment]
I started to get the same error just now. I was using an old version and when I saw this error, I downloaded the latest version but it still gives the same error.

**Comment by hama3254** [comment]
@pruebark9 for that episode you got there i did find a that the `download_hls` works here.
i can only hope this is the case for more episodes with this issue.
this means we now have 4 streams avalible the already used 3 green ones and now the `download_hls` which i did not use because it's 720p at best but better than nothing i guess.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/851bd36b-a7c5-4f47-bf51-a45a86796ffd)

due to the 720p issue it may take a little longer to get the stream added because it's always the last one to be checked so you get the other 3 streams before it.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/f81bb6ee-93f3-4954-bc59-2f7aa6534e97)

**Comment by pruebark9** [comment]
> due to the 720p issue it may take a little longer to get the stream added because it's always the last one to be checked so you get the other 3 streams before it.

Thanks for the reply, now it works with the latest version :D

Another minor problem that has started is that in the Naming option, I had always had it set to ignore session 1 in the filename extras part. That is to say, the videos I was left with Name of the anime-Season number (except if it was the first one that in that case nothing came out)-Episode number.

But since a few days ago, I always get a "1" in the season number even if I have it set to ignore the first one. It started out of nowhere without touching any option and now, there is no way to set it to work as usual. 

![Captura de pantalla (2)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/92517051/bcfcef2c-a66b-4fc0-90a5-e9b2f913fcc8)

**Comment by janiacteia** [comment]
The application is closing by itself and it is not my computer two versions before it did not close.
