### ISSUE TITLE
The download process seems to have crashed, download hangs on hybrid mode

### ISSUE THREAD

**Issue by D0ugyB0y** [hama3254/Crunchyroll-Downloader-v3.0#75]
I seem to be having issues with downloading from funimation, keeps showing that the download has crashed.
<img width="595" alt="hangs" src="https://user-images.githubusercontent.com/73110502/96442467-1915e800-1203-11eb-8211-1df067b2fc7f.png">

log file
[Talentless Nana Season 1 Episode 3.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5401297/Talentless.Nana.Season.1.Episode.3.log)

Also hangs when using hybrid mode, downloads and creates part file then doesn't join them.
<img width="602" alt="hangs" src="https://user-images.githubusercontent.com/73110502/96442705-76119e00-1203-11eb-8297-a477bc2d5384.png">

log file
[By the Grace of the Gods Season 1 Episode 3.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5401305/By.the.Grace.of.the.Gods.Season.1.Episode.3.log)

**Comment by hama3254** [comment]
booth is the same error : `HTTP error 403 Forbidden`
ffmpeg just cant access funimation stuff sometimes while the normal browser and the downloder can, thats the reason why the hybride mode fails after the download itself has completed because you use the "Merge subs with video file" setting which is not cached yet (coming soon).
The hybride mode can be fixed by disabling the the "Merge subs with video file" setting for now. 
for normal download keep looking for a solution but i don't really whats wrong with ffmpeg or funimation right now

**Comment by D0ugyB0y** [comment]
That option works well, there is another app I use (Youtube-DL) but it has issues grabbing the subs but ffmpeg connects and downloads 99% of the time, it uses your current cookie for the funimation login and only gets the 403 error when it expires. maybe that could be the cause with your downloader maybe?

**Comment by hama3254** [comment]
I can try if I can forward the cookie to ffmpeg but the strange part is I can access the subtitles from your log file in my browser without anything special (except my us VPN ).

**Comment by hama3254** [comment]
i tested a little bit with ffmpeg and think the problem was just the user agend, i changed it to an normal browser so the server should not return 403 forbidden anymore.
v3.5.5 with that change is now online

**Comment by D0ugyB0y** [comment]
[By the Grace of the Gods Season 1 Episode 3.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5411425/By.the.Grace.of.the.Gods.Season.1.Episode.3.log)

I've just tried the new released version but still shows the 403 error, weird.

**Comment by hama3254** [comment]
Strange, my test have been all successful.
I test it again today maybe the subtitles are different than the video stream.

**Comment by hama3254** [comment]
ffmpeg drives me crazy ...
you can and really need to add the `-headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"` for each input file

**Comment by hama3254** [comment]
> 
> funi has been having issues lately, the hybrid mode works well. just have to convert the .vtt subfile to .ass so i can customise the font etc.

i'm not sure what you want to tell me with that because the log indicates that you merged the subs directly with the mp4 file.
`20/10/2020 21:46:27https:[...]2010.vtt: Server returned 403 Forbidden (access denied)` 
that would explain why my tests where successful with v3.5.5 because ffmpeg really needs the user agent for each input.

but anyway if it is working then i can close that issue ?

**Comment by D0ugyB0y** [comment]
what i'm saying is the original issue still hasn't been resolved, but works when both subs and video are downloaded separately which you suggested so i'll just stick to using that method. when trying to download and merge subs automatically it still came up with the download process crashed. i'll close the issue anyway, thanks.
