### ISSUE TITLE
Crash when trying to download a certain episode from Crunchyroll

### ISSUE THREAD

**Issue by guitarjorge24** [hama3254/Crunchyroll-Downloader-v3.0#777]
There's a crash when trying to download episode 11 of The Ancient Magus' Bride Season 1
https://www.crunchyroll.com/watch/GR9PQ5G86/lovers-ever-run-before-the-clock

I tried about 5 times and it happens every time. Other episodes from the same season download properly. Only episode 11 causes the crash.

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings English softsubs
 - Version [e.g. v3.8.7.2]

**Comment by hama3254** [comment]
i don't see anything wrong with that episode.
please check that you have the latest version and if it still does not work than please provide the [FFMPEG-Logfile](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile) for this entry.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/fd6160d3-c9ff-4553-b9c0-ec90ce493bc7)

**Comment by bybpow** [comment]
Same here:
https://www.crunchyroll.com/es/watch/GN7UDWNP2/end-of-terminus-exams--girls-talk

It happens to me when the dub is Japanese.

**Comment by hama3254** [comment]
@bybpow i would need more data on that to know what is wrong because it does not happen for me.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/1ca6150f-b544-4f77-a4de-1322fba58c4f)

**Comment by bybpow** [comment]
What Can I provide? Settings?
As the app crashes I can't provide a logfile.

**Comment by hama3254** [comment]
> As the app crashes

oh the whole downloader crashes?
windows should do log of that in it's event view.

You should find the log here (my windows is set to German but it should look similar) 
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/54f319ed-fe96-4642-b55c-7246eb158ae4)

**Comment by bybpow** [comment]
This is the log and the exported events. Hope this is helpful.

![2023-07-02 18_53_36-](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/62562341/fc45a124-fdca-434d-8805-38eafb835fa3)
[crdl.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/11930122/crdl.zip)

**Comment by hama3254** [comment]
@bybpow i added [Crunchyroll-Downloader-v3.15.5.2.zip ](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.15.5) with some changes to a retry function.
i assume that retry function gets called since it goes from `Crunchyroll_Downloader.Main.GetCRVideo` to `Crunchyroll_Downloader.Main.LoadBrowser` which should only happen there.

I also want to note that the event states `Version: 10.0.19041.3155` which should be Windows 10 2004 and the downloader is not tested on older Windows 10 build. 
i currently use :
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/3b9d9cd5-fc2d-4fd3-a9a0-e596174f5094)

**Comment by bybpow** [comment]
I updated. The new fix solves the crash problem but the ep. still doesn't download. Same with ep. 14 so far.
[v3.15.5.2.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/11931367/v3.15.5.2.log)

**Comment by guitarjorge24** [comment]
> i don't see anything wrong with that episode. please check that you have the latest version and if it still does not work than please provide the [FFMPEG-Logfile](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile) for this entry.

Hi, I do have the latest version 3.15.5. It looks like  if I delete my user.config file then it doesn't happen anymore so it requires a particular setting.

I have attached my user.config here:
[User.config.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/11931666/User.config.zip)

and here's my log
[crunchy downloader log.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/11931667/crunchy.downloader.log.txt)

**Comment by guitarjorge24** [comment]
yeah, it looks like after I wipe the settings it works and then if I change the softsubs to "english" then it crashes:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/12472021/45312945-bbdf-4070-ab2a-e3ddba68882e)

**Comment by hama3254** [comment]
i found the issue with those two episodes, it only happens with unmerged englisch subtitles since they containt either of those 

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/976c1275-ff1a-4001-b0bb-8d838588585d)

this lead to the issue since error are reportet like this 
`curl: (22) The requested URL returned error: 400`

and everything behind the `:` can change so in my infinite wisdom i used `curl` to dectect issues.

This should however not make the downloader crash fully so i also remove the retry function and add a discalmer to finish running downloads and then to restart the downloader.

**Comment by hama3254** [comment]
the release has an updated version now.

**Comment by guitarjorge24** [comment]
lol I see, that happens! it's working for me now, thanks

**Comment by luccaslil** [comment]
![Captura de Tela (1)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139336136/9c6e9d3d-8d25-4b1b-b0aa-808027ccd9f3)
 help pls

**Comment by bybpow** [comment]
Are you logged in to the browser? Share the URL to try to reproduce.
