### ISSUE TITLE
cut video

### ISSUE THREAD

**Issue by Kimitaku** [hama3254/Crunchyroll-Downloader-v3.0#782]
I'm trying to download one piece but the video just cuts off, every 5 seconds it skips, any solution?
I tried lowering the resolution but the problem persists

**Comment by hama3254** [comment]
The details why this happens could be found in the [ffmpeg log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile).
If you don't use the `Hybrid Mode` already then enabling it should help a lot, but never had someone claim to have this happen this much since that would mean every 2nd fragment of the video fails to download for some reason.

**Comment by Kimitaku** [comment]
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/77254043/dd6465a9-08e2-4468-b23f-2e7b5e6dfead)

**Comment by Kimitaku** [comment]
the error does not occur when i connect via ethernet, but it does occur when i connect via wifi

**Comment by Kimitaku** [comment]
Tried to use hybrid mode and it gets worse

**Comment by hama3254** [comment]
This is a new one.
Can you check the exact windows version?
(Just type `winver` into the windows search and press `Enter`)
The issue seems in the connection encryption where I have not much access to.

**Comment by Kimitaku** [comment]
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/77254043/20bc3673-f701-455a-b50d-f94c8d4282ca)

**Comment by hama3254** [comment]
Since the Windows version is fine there is nothing to do here.
The issue is the encryption between the client and the server which i have no access to.

**Comment by Jaynator495** [comment]
I think it's more an issue with not properly handling (internet) packet loss.
