### ISSUE TITLE
European account + usage of a vpn

### ISSUE THREAD

**Issue by TheWizard-maker** [hama3254/Crunchyroll-Downloader-v3.0#786]
I am using a european account. Here is all the dub/subs I can have 
![crunchy](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/4b9c7489-9342-4878-8e8b-ebcdc3f1704a)
Is there more audio and subs available if i use a vpn to locate in US or somewhere else ? Is it possible to download them with this downloader ?

Thanks in advance

**Comment by hama3254** [comment]
The option in the downloader has listed all languages known to me and you can select them without any check for availability.
The option has no real effect without the checkbox below since all urls for crunchyroll have a fixed dub and only checking the option makes the downloader look for an alternative version.
If the selected dub does not exist the downloader will just use the url as with the dub as the url contains.

CR has some Geoblocking which VPNs can help with but they can also cause a lot of issues with cloudflare and should not be used.
