### ISSUE TITLE
parts that the video skips.

### ISSUE THREAD

**Issue by nicooc18g** [hama3254/Crunchyroll-Downloader-v3.0#798]
crunchyroll

I'm sorry but I can't take a screenshot because it's a problem with video downloads and no error panel appears for that reason

When you download some chapters they download wrong and when you play the video there are parts that the video skips. I would like you to fix that problem, it always happens to me or I would like you to tell me the solution if there is, please

**Comment by hama3254** [comment]
this issue is mostly due to the underlying technic of the streams.
The video stream is usually split into 2 seconds parts, if something interrupts the transfer of the part you experience such an issue.

To reduce the problem there is detection build in (as explained in #794).
This only detects issues, with the `Hybrid Mode` option in the `Output ` we have the an alternativ download method.
Without to much explanation, video processing is hard so i use a finished tool (`ffmpeg.exe`) which limits my options.
There the hybrid mode comes in, i cache the stream local with my own code so the downloader does retry failed segments of the stream one time and i have a much higher timeout than `´ffmpeg` (~6 seconds for `ffmpeg` vs 30 seconds for the hybrid mode).

**Comment by San3-Cod3** [comment]
@Tobolobo - It would be great for you to officially publish that code on your GitHub page before it expires in 100 or so days - it would be great to turn this into a fully fledged GUI for different languages like C#, and Python to check for skipped frames - it would be great to build it into a great application with help from the Community.
