### ISSUE TITLE
Video cut before the end.

### ISSUE THREAD

**Issue by nigoki2** [hama3254/Crunchyroll-Downloader-v3.0#802]
Hi.
Some softsubbed videos from Crunchyroll are cut before the end, like The Devil is a Part-Timer! Season 2 Episode 19:
Download with Crunchyroll-Downloader-v3.15.6.1:
<a href="https://ibb.co/zrFF91T"><img src="https://i.ibb.co/zrFF91T/Capture1.jpg" alt="Capture1" border="0"></a>

Rip from [Tsundere-Raws]
<a href="https://ibb.co/Z2c8Qhp"><img src="https://i.ibb.co/Z2c8Qhp/Capture2.jpg" alt="Capture2" border="0"></a>

This problem does'nt affect all videos but only some.

Thank you.

**Comment by hama3254** [comment]
I am not sure what the issue here. I get the same result but the downloader seem to work fine.
My main problem is that the [streams the downloader uses](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/748#issuecomment-1574908351) give this issue as i stream them directly using VLC.
The website is fine since they use something differnt entirely by now (see #740).
