### ISSUE TITLE
Is it possible to select more than one audio for the file download?

### ISSUE THREAD

**Issue by kazrhak** [hama3254/Crunchyroll-Downloader-v3.0#816]
I am using version 3.5.17, I wanted to know if it can be configured to download more than one audio.

I only see the option to download several subtitles, but for the audio I can only select one audio.

Is it possible to select more than one audio for the file download?

Thanks!!

**Comment by kazrhak** [comment]
Hello, you saw that comment [# 735](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/735) talked about this topic.

From what you understand, right now it is NOT possible to download a chapter with more than one audio, so what you should do is:

1º- Download the chapter in Japanese language, with the subtitles we want.
2º- Once downloaded, download the chapter in another language (for example Spanish, Spain).
3º- In the options, have the "Merge audio with existing files" option checked.
4º- The final result will be a .mkv file with the two downloaded audios and the subtitles of the first downloaded chapter.

Would this be the correct process? Or should it be done another way?

Thank you so much.

**Comment by hama3254** [comment]
This process is more or less the current option you have.
#701 adds lists known issues which are partially the reason why there is no automatic way to do this.


> 1º- Download the chapter in Japanese language, with the subtitles we want.

I would add that soft-subtitles are preferably here.


> 2º- Once downloaded, download the chapter in another language (for example Spanish, Spain).
> 3º- In the options, have the "Merge audio with existing files" option checked.

The merge option is a drop-down on the `add video` dialog and should be selected before starting the second download.


> 4º- The final result will be a .mkv file with the two downloaded audios and the subtitles of the first downloaded chapter.

I personally never tested `mp4` but I would recommend `mkv` just for the soft-subtitles from the first step.

**Comment by kazrhak** [comment]
Hello @Hama3254, Thanks for the reply, so the correct process would be like this?

The first download has this configuration:
* Tab Output with Format MKV and with Merge Disabled

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/58183590/1c258052-b17c-4fb3-8d7d-f52cd250fc26)

*Tab Crunchyroll with Dub Japan and with softSubs
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/58183590/e99e92da-2ec4-45f3-abc3-f84fe142e9ec)

*The others tab by default

*And finally, this:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/58183590/6fbe213e-8818-43ca-9f7f-e4994b446b90)



This configuration downloads the chapter with Japanese dub and with English And Spanishs subs, everything is correct.
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/58183590/42038f35-01c8-4de0-93fb-3ab2138eb812)

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/58183590/4d377ddd-6eb3-40a3-b867-fce6b8133b88)


Now we go with the configuration of the second download, to add another audio:
*The tab Output with Format MKV and with copy (copy or Merge disabled?)
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/58183590/1a530546-b18c-4309-8a93-ed166a2fad43)

* The tab crunchyroll with dub Spanish and with check override Dub language and without softSubs.
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/58183590/7759fef7-fcdf-4584-abf0-a036beb8bc49)

*And finally this, with Merge Audio with existing files:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/58183590/c93c192a-0467-40fe-b5e7-555ced0c87be)

This configuration downloads the chapter with Spanish dub and without subs, everything is correct.
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/58183590/b535f3a6-5b02-4721-883a-3e1120733ed3)


The problem I have seen is that at the end of the second download, the .mkv file from the first download is renamed, and I have a .mkv file with Japanese Dub and another .mkv file with Spanish Dub 
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/58183590/bb36013e-bb58-443d-b2f5-0aec2df000b8)





**Would this way of downloading be correct? Or is there a step I should change?**

**Comment by hama3254** [comment]
> The tab Output with Format MKV and with copy (copy or Merge disabled?)

`copy` would add the subtitle file into the `mkv` file while the other saves it into the same folder.
I personally would use `copy` and for my japanese only downloads I use the default subs (on the Crunchyroll tab) to tell the player that I want the subs on directly. Here you need to find your preference.

You should also not need to change the settings depending how you get the url.
If you uncheck the override dub option makes the download use the episode default which is the exact same as you have in the Browser because of you switch it on CR the URL also changes.

For single episodes would this mean you setup the download like it is on the top (merged subs if you want) then add the episode while it's downloading you can set the language on the player in your browser to Spanish the url changes and now you just have to wait for the first download to finish before adding the 2nd audio source.

It also should be possible to keep the merge option at all time because it should not trigger any merge if there is nothing to merge with.

If your settings work fine for you season downloads should also work pretty simple by using the URL of the overview for all episodes the download can request the different version and will display the season and dub (if CR has the right data).

So you could just let run a full season download with japanese selected and then just add it again but use Spanish.

Note: this only works if CR does not mark the dubs with different season which has happen in the past (shield hero had German dub marked as season 9 for a while)

**Comment by kazrhak** [comment]
Thank you very much for the help, now you understood the difference in subtitles.

But I still have the problem that when I download the episode in different audio, it doesn't merge them into a single .mkv file.

Now for each audio of an episode it does not modify the CRD settings, but rather I take the CR URL for each audio. That is, the CRD settings are the same for everyone, only the CR URL changes for each audio.

When I get the URL of the audio in Spanish, the episode is downloaded correctly with the audio in Spanish and the subtitles integrated into the .mkv file.

Once downloaded, I take the URL of the same episode but with the audio in Japanese, and activate the "Merge audio with existing files" option.

The result is that the first downloaded chapter (in Spanish) is renamed with the name TEMP, and the chapter with the correct name only has the Japanese language (the last downloaded language), the merge is NOT done correctly.


Am I doing something wrong or could it be that the audio fusion is not working correctly?

I understand that the result should be a single file with both audios and all the subtitles.


Thanks!

**Comment by hama3254** [comment]
> The result is that the first downloaded chapter (in Spanish) is renamed with the name TEMP, and the chapter with the correct name only has the Japanese language (the last downloaded language), the merge is NOT done correctly.

Renaming the old one is fine and required since I can not use the same file as input and output.
This also means the merge gets called and there need to be something wrong with it.

A great help would be the [FFMPEG-Logfile](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile).

**Comment by hama3254** [comment]
you may need to switch to `Hybrid Mode` for it to work correctly.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/60ee8290-b435-40f8-ba3c-2ad3fce88600)

**Comment by HenryKUNliao** [comment]
Hi everybody. I just wanna say you could also download the episode in both languages and then mix the audio files with mkvtoolnix.
In that way you will have a single mkv file with both audio options and the diference in weight is minimal.
