### ISSUE TITLE
Episode name

### ISSUE THREAD

**Issue by coldbrew02** [hama3254/Crunchyroll-Downloader-v3.0#817]
Is there any way for the episode name to appear in a language other than English?

**Comment by hama3254** [comment]
For the actual name of the episode it should take the name from CR like here `Die Welt von Remnant 1 Dust`.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/ba6d91b7-b5cb-4755-9687-09785d6c2a7c)

If you mean the `Season` and `Episode` part that are defaul values since CR has none for them, you can change those prefix here.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/f0835a8e-b5f5-4d68-a78e-8b93bece8f95)
