### ISSUE TITLE
Support for Ubuntu?

### ISSUE THREAD

**Issue by philipm92** [hama3254/Crunchyroll-Downloader-v3.0#847]
Hi,

title says it all. Do you ever plan to make a version for Ubuntu?

**Comment by hama3254** [comment]
I never tested any Linux distro since the switch to the `WebView2` which is from Microsoft and is based on Edge.
Like i said in #842 i use the Browser to take care of all cookie handling (login, cloudflare) and just pull the cookies for requests.
You might get it to work with Wine but i never tried.
