### ISSUE TITLE
Subtitles are streched

### ISSUE THREAD

**Issue by dqfwfqfqf** [hama3254/Crunchyroll-Downloader-v3.0#850]
For some reason, whenever I download something, while the video is fine, the subtitles are stretched like below
![Screenshot 2023-12-09 184548](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/153386168/d4f688b4-ef2e-438e-b3a7-56e7a06ee142)
These are my settings
![Screenshot 2023-12-09 184432](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/153386168/72af700a-4407-4789-ae4c-3f07990b7591)

This always happens when the video format is mkv (Even when the merge option is disabled), but if it's an mp4 video, the subtitles are fine

**Comment by Elwador** [comment]
i am guessing you try to watch the mkv files with VLC? because when using VLC they are streched for me as well but they are fine with everything else

**Comment by dqfwfqfqf** [comment]
I am using Vlc, but I don't think the problem is from it, as I said if I download the subtitles as a separate file with mp4 format, subtitles are fine. I guess that something happens during post-processing that causes the issue.

**Comment by hama3254** [comment]
Other than the `ScaledBorderAndShadow:yes` option (see #764) i do not edit the subtitles.
`mp4` might change something if merged since it does not support `ass` but that happens inside `ffmpeg`.

`ScaledBorderAndShadow:yes` did solve the issue for me.
Keep in mind that the downloader can not modify the subtitles with our settings.
Like added to #764 only unmerged subs or `Hybrid Mode` downloads allow me access to the text directly.

**Comment by dqfwfqfqf** [comment]
I have tried downloading with `Hybrid Mode`, and it fixed the issue so probably something with `ffmpeg`.
