### ISSUE TITLE
Subtitles have an odd size

### ISSUE THREAD

**Issue by pbz134** [hama3254/Crunchyroll-Downloader-v3.0#855]
**Describe the bug**
After downloading a Crunchyroll video with softsubs, the subtitles' size appears too big and oddly stretched.
Editing the "PlayResX" and "PlayResY" values in the .ass file manually kind of fixes this issue
 I attached the subtitles (.zip) here for people to inspect.
 
 Edit: I found out that converting the .ass file to .srt fully fixes this issue, but no way to directly get this file type from the downloader afaik.

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings Hardsubs none, Softsubs German and English, remove CC style disabled
 - Version v3.15.7.2

**Screenshots**
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/53271427/65cf9124-0ab9-4a73-8c98-efaae9430708)
[YuruYuri PV.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/13685950/YuruYuri.PV.zip)

**Comment by Davis092** [comment]
This happens in new versions of VLC (it happened to me weeks ago).

It shouldn't happen in two 3.0.9.2 .

**Comment by Anonymous327** [comment]
> This happens in new versions of VLC (it happened to me weeks ago).
> 
> It shouldn't happen in v3.0.9.2 .

That's actually incorrect if you open the subs in a subtitle editor. The ASSA script resolution is wrong. It's downloaded as 360p instead of 1080p. The subtitle resolution should change depending on which video resolution you choose (because the size of subs will change depending on the resolution of the video, of course. This seems like bug that did not exist when I first started using the program.
