### ISSUE TITLE
resolution (1080p) not found

### ISSUE THREAD

**Issue by TheWizard-maker** [hama3254/Crunchyroll-Downloader-v3.0#885]
while donloading tokyo revenger with Portugues Brasil dubs. The downloader cannot find the video with a resolution of 1080p for episodes 13, 14 and 15 and ask to select a lower one. Is that a bug of the downloader ? it is unexpected that only 3 episodes have a lower resolution

**Comment by hama3254** [comment]
> Is that a bug of the downloader

I have not seen any behavior of the resolution selection that would be wrong.
Issues always came due to bad data from CR, some shows report `1920x1079` or `1920x800`.

We would have to check the specifics here but I nether have the raw data right now (at work) or the drop-down options given to you.


> it is unexpected that only 3 episodes have a lower resolution

I have seen some variation in there data before where the same request (same anime and season) returned different data so I am not surprised by CR anymore.

**Comment by hama3254** [comment]
CR also only displays up to 720p for me.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/701ac6c2-818f-44c6-a501-e06d413f6c97)
