### ISSUE TITLE
Unable to download anything as of today.

### ISSUE THREAD

**Issue by junkoe** [hama3254/Crunchyroll-Downloader-v3.0#906]
**Describe the bug**
As of today when I try to download any title, premium or not I get the following popup error message.

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/826453/02c3bc11-b58b-4d8e-96cb-31631416d191)

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings Same as I have been using which are:
 Hardsubs - Null, Softsubs - English, ffmpeg- Hybrid option MKV format]
 - Version v3.17.2

**Screenshots**
Please see the image above.

**Additional context**
These settings have been fine but just as of today it's no longer working. I have a premium account, I am logged in. I even logged out and back in with the built in browser, I left the browser tab open and closed. No matter what it just seems to spit this error and fail. It seems like something changed today, but what that is I do not know.

**Comment by Primelikes01** [comment]
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/158451701/2c91217c-63da-4bcf-a100-10a92a99f9b3)

**Comment by hama3254** [comment]
@junkoe i just closed issue #900 with the same error (because no respone).
I am still unable to reproduce the issue.
Downloading [a random RWBY](https://www.crunchyroll.com/de/watch/G69PX0W3Y/world-of-remnant-1-dust) episode (Premium only) works fine with a premium account and gives the right error message if logged out or without Premium.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/59ee95dd-18df-42cb-925d-9b006f0c7329)

I also tested the free [Solo Leveling](https://www.crunchyroll.com/de/watch/G14U415QM/im-used-to-it) episode and that works logged out just fine.

issue #900 mentionded a VPN so this could be a cause but i was unable to verify that.

**Comment by hama3254** [comment]
@Primelikes01 for future issues please open your own issue for unrelated problems.

To the issue, it seems like this is a [crul](https://curl.se/) issue.

You can try to get the [`cacert.pem`](https://curl.se/ca/cacert.pem) from curl and replace the existing `curl-ca-bundle.crt` with it.
You can see the exact path in the error message.

**Comment by Primelikes01** [comment]
> @Primelikes01 for future issues please open your own issue for unrelated problems.
> 
> To the issue, it seems like this is a [crul](https://curl.se/) issue.
> 
> You can try to get the [`cacert.pem`](https://curl.se/ca/cacert.pem) from curl and replace the existing with it. You can see the exact path in the error message.`curl-ca-bundle.crt`

Sorry,

**Comment by Primelikes01** [comment]
Thank You, problem solved ❤️💕

**Comment by junkoe** [comment]
I appreciate the response, I did have a VPN on but I had used this VPN the entire time that it was working before.

I tried today without the VPN and the same issue occurs.

I am not sure what changed, my only thought is that perhaps it's because I am currently on the free trial still and I hit some kind of limit?

**Comment by hama3254** [comment]
i added [v3.17.3](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.17) which should now display a messagebox with the Url that triggers the issue and the option to continue with the `Ok` button.

**Comment by MLB-11** [comment]
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/98657556/21a6fc06-ec12-4833-b5df-6b3c3aece315)
