### ISSUE TITLE
URL delete / Shortcut for ID

### ISSUE THREAD

**Issue by progithub2** [hama3254/Crunchyroll-Downloader-v3.0#928]
Hello hama3254, 

1. would it be possible to add an button to delete the input in field "URL" after you set it to download (or delete it by clicking on download)?
2. would it be possible to enter only the id instead of the whole url? 

best progithub2

**Comment by hama3254** [comment]
> 1. would it be possible to add an button to delete the input in field "URL" after you set it to download (or delete it by clicking on download)?

this is possible but as just a UI thing very user specific, i for example never thougt about it since i use series links most of the time (or it crashes because of some issue while development :/ ).
I can delete the text field like i do with the `URL` placeholder but should i and then when? 
Deleting it directly removes information from the user until the download is added, later when the download is added the user might already added a new url.
So i think i keep it as it is for now.

 
> 2\. would it be possible to enter only the id instead of the whole url?

Not really, the downloader can process both series pages and direct episodes and the Url is the best way to detect that.
Also copying the Url from your Browser is much simpler than just any ID so why would you even want that?
