### ISSUE TITLE
The download process seems to have crashed and no log file being created

### ISSUE THREAD

**Issue by Fpsroxas** [hama3254/Crunchyroll-Downloader-v3.0#94]
1ºWith this new version 3.6 whenever I start a download they instantly fail.
2º For some reason I can't produce any log files even if the option is activated, no files are created.
![image](https://user-images.githubusercontent.com/45643566/100949032-11c34900-34e8-11eb-82a4-da421795cff4.png)

**Comment by hama3254** [comment]
The Anime itself work perfectly to download for me, what does not work is the old version of the subfolder since i changed how it work. If you have `[automatic : Series/Season]` selected as subfolder please change it to one of the other `automatic` modes then it should be working.
![grafik](https://user-images.githubusercontent.com/52826614/100992264-42d96300-3554-11eb-92fc-b1ec41304125.png)

**Comment by Fpsroxas** [comment]
I tried with all the subfolder options and it gave an error in all but for some reason when I activated the hybrid download it started to work.
I don't usually use this mode because I download faster with it disabled.

**Comment by hama3254** [comment]
> I tried with all the subfolder options and it gave an error in all but for some reason when I activated the hybrid download it started to work.
> I don't usually use this mode because I download faster with it disabled.

Did `[ ignore subfolder ]` also not work?

the other two options work fine for me 
![grafik](https://user-images.githubusercontent.com/52826614/101043653-d2940700-357e-11eb-8c66-c6b288d4b1b9.png)

**Comment by hama3254** [comment]
For debugging please try to make two double clicks on the settings icon, a message box with `Debug activated`  should aper.

You can now try one episode and just after it get added to the list there should be a message box look like this 
![grafik](https://user-images.githubusercontent.com/52826614/101045039-4682df00-3580-11eb-9418-0d23f3239a76.png)
Please send me a screenshot of that box including the subfolder settings you had.

**Comment by Azul772** [comment]
Crunchyroll Downloader 3.6 version
1) I used hybrid mode and as soon as it reached 100% it crashed
2) I did not use hybrid mode and it just stopped downloading
in both cases I have use "ignore subfolder" and "automatic: by series"
<img width="653" alt="error" src="https://user-images.githubusercontent.com/75436296/101045899-02c7af80-3557-11eb-8651-932378ee65b5.png">

**Comment by hama3254** [comment]
> 2º For some reason I can't produce any log files even if the option is activated, no files are created.

are there still no logfile ? 
This look different than i expected with 

> I start a download they instantly fail.

There is a difference between crash due to missing/wrong folder and just process crashes.

**Comment by Fpsroxas** [comment]
> Did `[ ignore subfolder ]` also not work?
yes even the ignore subfolder doesn't work
![Captura de tela 2020-12-03 125448](https://user-images.githubusercontent.com/45643566/101053981-2692f180-3567-11eb-85b1-9e0ae1134e89.png)
![Captura de tela 2020-12-03 125516](https://user-images.githubusercontent.com/45643566/101053998-2b57a580-3567-11eb-93de-3e73f002a295.png)

**Comment by hama3254** [comment]
Thanks, i now see the problem, it is the name `O divergente na Academia Rei Demônio` the browser uses UTF-8 to display the correct name while the html is plain text and looks like this  `O divergente na Academia Rei Dem\u00f4nio Epis\u00f3dio 1` and since non of that characters is invalid on it's own it just crashes because the path is invalid.

A quick fix should be to use the english version from crunchyroll while i'm fixing this issue, you can to that by replacing the `pt-br` in the url with `en-gb`. This will affect the name to be in English but the selected subtitle language will stay as it is set in the downloader settings (in your case Português (Brasil) )

**Comment by Fpsroxas** [comment]
Got it!
Thanks for your help I really appreciate it.
Sorry for the problem.

**Comment by hama3254** [comment]
This issue should now be fixed with v3.6.2. You should now be able to download the Episode even with the Unicode characters.

**Comment by Fpsroxas** [comment]
Tested 100% working
