### ISSUE TITLE
question about the process queue

### ISSUE THREAD

**Issue by Vorffeed** [hama3254/Crunchyroll-Downloader-v3.0#948]
is there any way to leave the process queue automatically activated all the time, and not have to activate it every time I try to put many links at once?

**Comment by hama3254** [comment]
If you understand you correctly, you add episode after episode and the downloader does not keep up and they get added to queue.
This means you have to open the queue and start it from there.
I am not sure how the queue behaves, you can not use the season download with the queue because it gaves problems.
Depending on what you want to achieve and the documentation being practical non existent I would recommend to use a overview url for the download.
This gives you a selection for the Dub and season from what is available to just add it all.

**Comment by Vorffeed** [comment]
I was referring to this option that if there is any way to initialize it directly activated without having to open it always and activate it, because it is much more comfortable when it comes to go putting links from different series and not as the preedetermianda form that you have to delete the link you just added to put the next link because it does not disappear as when you activate this mode.
Since I usually download all the daily episodes I am interested in watching, and I put them all at once, and with this mode activated it is much faster when adding them.
Although I would appreciate a mode like the process queue where you could see all the links added, but where you could paste all the links of the single chapters at once and hit start and it would process everything as this mode does after adding them one by one.
I hope I have explained well
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/10000442/204ad58a-a293-4519-9448-436d283e74d1)

**Comment by hama3254** [comment]
After some tests i don't understand this request.
Once enabled the queue processes links that got postponed capped by the download limit.
The queue also stays on after it is empty, so you can start the queue from the very beginning and add all episodes you need.

**Comment by Vorffeed** [comment]
Let's see if I explain well, when you put a link it stays when you click on download, and you have to delete it to put the next one, instead when you activate the queued processing mode, you add links more comfortably because you don't have to delete the link you have put first because it disappears, to put the next one, that's why I was asking if there was an option to leave this mode activated.
because you have to leave the tab open because if you close it the process does not continue and you must reopen it and click again on the process queue to continue, it seems to me a more comfortable process for those who put 10-15 links in a row at once, because for those who only download an episode or two the normal mode will be fine, but for those who put many single episodes every day at once is fatal, that's why I also said to enable a box to put all the links at once and hit accept and process in the same way that appears in the process queue.

**Comment by hama3254** [comment]
Just as idea, adding a "hidden queue" that can be activated in the settings. This could make the downloader run like in the queue without the queue window visible (cheating by removing the icon in the taskbar and moving the window to -10000px -10000px) 
Any feedback is welcomed.

**Comment by Vorffeed** [comment]
That was exactly one of the options I was asking for.🥰

**Comment by hama3254** [comment]
You can test out [v3.23.2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.23.2) the settings now has the `hidden Queue` option.
This will toggel and lock the orange option since the Queue is not compatible with the multi download.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/b54b261c-552f-4fcb-89bd-3129a7e5471f)

The queue is not visible on the screen but the window is inside the taskbar, also if you click on the queue button the queue will appear. 
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/c8aabf53-8fa3-40fc-bf5e-59acf80ea653)

if the queue is visible (after you open it manuel) it behaves the same as usuall.

**Comment by acteiaa** [comment]
I also really wanted this option; every time I had to open several CR Downloads to download dual-audio. Thanks <3

**Comment by Vorffeed** [comment]
Thank you I will try it 😍

**Comment by jesuspkane** [comment]
the rrequested url retorned errror 403 that is the error it gives

**Comment by hama3254** [comment]
since there are no further questions or issues with this feature i will close this.
