### ISSUE TITLE
Problem with Funimation

### ISSUE THREAD

**Issue by yentcadan** [hama3254/Crunchyroll-Downloader-v3.0#95]
When I try to download LATAM Funimation episodes, this error windows shows up.
![Screenshot_1](https://user-images.githubusercontent.com/71165561/100953780-04ab5780-34f2-11eb-932b-7dc9dc0de577.png)

**Comment by hama3254** [comment]
i'm not sure what "LATAM Funimation"  what i found would be the sub domain `latam.funimation.com` which i never have heard before. 
The downloader is only written and tested for funimation.com which should get you the language of the country you are in (or at least they think you are in...) so i don't get why a subdomain even exist. 
Please let me know if you even mean the subdomain with "LATAM Funimation" and what is even different to the normal funimation.com website.

**Comment by yentcadan** [comment]
LATAM Funimation is the version of Funimation for latin america, in my case I'm using the Brazilian domain <https://www.funimation.com/pt-br/> and it's showing this error.

**Comment by hama3254** [comment]
If that is the case then the Domain should be fine, but i would need to know the exact url you tried to see why it broke i the middle of the name search. 
Please notice that you can not add Anime from the Overview at funimation, you need to add the direct episode url.

**Comment by yentcadan** [comment]
Oh, that is the problem then, I was trying to download by the catalog like Crunchyroll, and when I say Crunchyroll, I can download even without have a subscription?

**Comment by hama3254** [comment]
You can download everything you have access to.
The adding from the overview does just not work that easy due to the fact that they load it via Javascript, [but you can try this](https://youtu.be/18qBIUYdlEM) or [you could give the add-on a try](https://youtu.be/ZHCH3rNWYS8) 
You just need to ena
[Get it for Chrome](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/Chrome-add-on-guide)
[Get it for Firefox](https://addons.mozilla.org/en-US/firefox/addon/crunchyroll-downloader-addon/)
