### ISSUE TITLE
The cache files seems to occupy space until the PC is restarted

### ISSUE THREAD

**Issue by ben10092001** [hama3254/Crunchyroll-Downloader-v3.0#952]
I downloaded some videos from Crunchyroll and my storage got used up and then the downloader said that I don’t have any storage left. I tries several things but in vain. The only thing that helped me was restarting the computer. But again if I download anything the problem occurs again. I also couldn’t find the cache files to manually delete it, even after searching the specified location.

**Comment by hama3254** [comment]
Please share screenshot of the error message.
I am not aware of any check from the Downloader for the available disk space.
If you don't have engough disk space then i would recomment to stay with the default download mode.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/6e264b71-a82d-451e-90aa-56e74c151817)

With the default settings one episode is about 1.4GB in size (for 1080p).

**Comment by ben10092001** [comment]
Edit: Actually I am downloading audios only. So that should take around 22 MB each. And I downloaded 24 audios. But somehow my drive used around 30 GB and that space didn’t get freed until I restarted my PC.

Nothing else was running in my PC that consumes disk space.

Is there any way I can share my screen recording with you ?

**Comment by ben10092001** [comment]
Okay. So, I started downloading Tamil Audio of SPY FAMILY Season 2.
<img width="1680" alt="Screenshot 2024-05-12 at 6 15 32 PM" src="https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/168761746/8d12173f-f2f4-4107-855f-07b74240d64f">

As You can see there is 16.2 GB available on my C: Drive

I selected 5 episodes to download

<img width="863" alt="Screenshot 2024-05-12 at 6 16 38 PM" src="https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/168761746/93a4b6e7-7104-4b94-987f-8c6749587eb8">
<img width="847" alt="Screenshot 2024-05-12 at 6 16 50 PM" src="https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/168761746/76bf805d-df01-4fea-8850-f0a30da5d04d">

And finally download completed

<img width="826" alt="Screenshot 2024-05-12 at 6 17 34 PM" src="https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/168761746/ec8e4571-4d92-4e22-8ab7-4a2db6ec7f30">

After this see my drive space now

![Screenshot (116)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/168761746/99d7e1f2-f9f9-47ed-b488-acaa48e2f64d)

2 Gigs got occupied after downloading the audio
The audio was just around 100 MB in size.

This space gets freed up only after restart.

Also if I open the program without restarting, this message pops up. I think it has something to do with the problem. Because this message doesn't appear if I start the program after restarting my PC.
<img width="421" alt="Screenshot 2024-05-12 at 6 17 40 PM" src="https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/168761746/abb12ea5-148d-4172-ae0c-36d566e672a3">

I can confirm that this has happened to me multiple times since v3.21 (the version in which Funimation code was removed.)
There was no such problem with releases prior to that.

**Comment by hama3254** [comment]
I checked the behavior and found only a minor issue with the current build.
Again the downloader only caches file with the `Hybrid Mode` otherwise `ffmpeg.exe` will download the data and i this case convert it into audio without writing it to the disk first.
Just now i checked v3.23.2 and it does delete the temp files for me. The only issue i found is that the temp path is not updated after chaning the path, a restart of the downloader or setting the temp path by hand should fix that.

I would recomment to create a new folder at your `E:` drive and select it both as output folder and as temp folder.
The Output folder can be changed by clicking at the path in the add window and [the temp folder can be a different path which is found here](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/952#issuecomment-2106027297).
