### ISSUE TITLE
Specific problem with anime on demand

### ISSUE THREAD

**Issue by Kyouma95** [hama3254/Crunchyroll-Downloader-v3.0#96]
First, thank you for supporting anime on demand.

The problem i encountered is specific to the series InuYasha. Previously they only had the episodes 1-40 and 105-167 available in 1080p with Japanese Dub and the episodes 41-104 only in 576p and German. Just recently they added the missing episodes with 1080p and Japanese Dub.

Now for the episodes which were always available in that format the download works just fine, but for the episodes which were recently added, i can only choose the 576p version. Do you have any idea and possibly a solution for this?

**Comment by hama3254** [comment]
That is not a specific problem, this is a bug due to a small change after everting was done. 
I locked the DropDown menus by disabling them but i did not notice that i checked if it disabled in the add function which then checked Dub first if there are streams available and then Sub and used the first one that could be found. 
this lead to the use of always Dub if it available so it used the low resolution Ger dub instead of the "1080p" OmU for you.

**Comment by Kyouma95** [comment]
Glad that you already know what's causing this. Gonna wait for the fix then, thank you.

**Comment by hama3254** [comment]
> Glad that you already know what's causing this. Gonna wait for the fix then, thank you.

the fix already done and can be found here : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.6

**Comment by Kyouma95** [comment]
Works very well, thanks.
