### ISSUE TITLE
Crunchyroll Downloader keeps downloading the wrong language...

### ISSUE THREAD

**Issue by VenonSabio** [hama3254/Crunchyroll-Downloader-v3.0#965]
**Describe the bug**
When I download my episode, it keeps downloading the Portuguese version of it...
I live in Portugal but I don't want to watch it in Portuguese, just Japanese
I also don't know why it says that hardsub is null when I selected it right, can someone help me?
Thanks in advance.

**Where does the issue happen?**
 - Platform: Crunchyroll [e.g. Crunchyroll, Funimation]
 - Settings: Dub [e.g. Hardsubs, Softsubs, ffmpeg options]
 - Version: v3.23.4 [e.g. v3.8.7.2]

**Screenshots**
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/135517798/a757ae34-6292-485b-b38c-b89b525b42de)
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/135517798/1c91e235-f8b2-4f51-9afc-840fe3e1c3cd)

**Comment by VenonSabio** [comment]
And yes, I tried to reset Crunchyroll Downloader settings, uncheck "override dub language", etc...

**Comment by hama3254** [comment]
I just check this and it seems the override is not working correctly.
The video url is unique for every dub, a quick workaround would be to set japanese inside your CR account.
This will give you the japanese url by default and the not working override is bypassed.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/d5e83987-8fcf-4bd9-a1ad-f1c62b2a84a4)

> I also don't know why it says that hardsub is null when I selected it right, can someone help me?

Dubs may not have subtitles at all like in thise case there is simply no hardsub version.
You should have gotten this error box to select `[null]`.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/5d154a0d-698f-4d97-9314-91e3698f6122)


Also the settings might not be optimal since you have both hard and softsubs enabled, this can lead to issues like #957.

**Comment by hama3254** [comment]
[v3.24.5](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.23.5) should now fix the override for good.

**Comment by VenonSabio** [comment]
> [v3.23.5](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.23.5) should now fix the override for good.

Thank you for the amazing service 🙏
