### ISSUE TITLE
About Accounts

### ISSUE THREAD

**Issue by MrFanservice-png** [hama3254/Crunchyroll-Downloader-v3.0#982]
Do you need a premium account to download premium videos, or will a free account will do just fine?

**Comment by hama3254** [comment]
You need a premium account for premium videos.

**Comment by stratuma** [comment]
Adding a premium check before login should prevent bugreports like this.

**Comment by hama3254** [comment]
> Adding a premium check before login should prevent bugreports like this.

We have a error message with a check if the `objects` API call has the old `streams` API listed.
This was a reliable indicator in the past since we needed that data anyway.
Now I use it to display a error message to check the login.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/blob/588fc587f2e8c4682d540ba73baeb5d429d7573b/Crunchyroll%20Downloader/Main.vb#L3013
